Repository broadinstitute/cromwell, pull requests merged in 2018-07, with the labels that each got.

#3832 Added localFileResolver to womtool
  languageFactories/language-factory-core/src/main/scala/cromwell/languages/util/ImportResolver.scala
  womtool/src/main/scala/womtool/input/WomGraphMaker.scala
  womtool/src/test/resources/validate/wdl_draft2/valid/relative_local_import/relative_local_import.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/relative_local_import/relative_local_import.wdl
Labels: 👍Red Thumb Required 🙏

#3677 WOM to draft-3 object models
  .travis.yml
  build.sbt
  centaur/src/it/scala/centaur/AbstractCentaurTestCaseSpec.scala
  centaur/src/it/scala/centaur/CentaurTestSuite.scala
  centaur/src/it/scala/centaur/UpgradeTestCaseSpec.scala
  centaur/src/main/resources/standardTestCases/composedenginefunctions.test
  centaur/src/main/resources/standardTestCases/conditionals.ifs_in_scatters.test
  centaur/src/main/resources/standardTestCases/conditionals.nested_lookups.test
  centaur/src/main/resources/standardTestCases/conditionals.scatters_in_ifs.test
  centaur/src/main/resources/standardTestCases/conditionals.simple_if.test
  centaur/src/main/resources/standardTestCases/conditionals.simple_if_workflow_outputs.test
  centaur/src/main/resources/standardTestCases/declarations.test
  centaur/src/main/resources/standardTestCases/declarations_as_nodes.test
  centaur/src/main/resources/standardTestCases/draft3_custom_mount_point.test
  centaur/src/main/resources/standardTestCases/hello.test
  centaur/src/main/resources/standardTestCases/object_access.test
  centaur/src/main/resources/standardTestCases/read_write_json.test
  centaur/src/main/resources/standardTestCases/scatterchain.test
  centaur/src/main/resources/standardTestCases/scattergather.test
  centaur/src/main/resources/standardTestCases/short_circuit.test
  centaur/src/main/resources/standardTestCases/square.test
  centaur/src/main/resources/standardTestCases/string_interpolation.test
  centaur/src/main/resources/standardTestCases/valid_labels.test
  centaur/src/main/resources/standardTestCases/wdl_draft3/custom_mount_point/custom_mount_point.wdl
  centaur/src/main/resources/standardTestCases/write_lines.test
  centaur/test_cromwell.sh
  src/bin/ci/testCentaurBcs.sh
  src/bin/ci/testCentaurWdlUpgradeLocal.sh
  wdl/model/draft2/src/main/scala/wdl/draft2/model/WdlExpression.scala
  wdl/model/draft2/src/test/scala/wdl/DeclarationSpec.scala
  wdl/model/draft2/src/test/scala/wdl/WdlWorkflowSpec.scala
  wdl/model/draft3/src/main/scala/wdl/model/draft3/elements/ExpressionElement.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wdl/WdlWriter.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wdl/WdlWriterImpl.scala
  wom/src/main/scala/wom/graph/ScatterNode.scala
  womtool/src/main/scala/womtool/WomtoolMain.scala
  womtool/src/main/scala/womtool/cmdline/PartialWomtoolCommandLineArguments.scala
  womtool/src/main/scala/womtool/cmdline/WomtoolCommandLineParser.scala
  womtool/src/main/scala/womtool/wom2wdlom/WomToWdlom.scala
  womtool/src/test/scala/womtool/WomtoolMainSpec.scala
Labels: 🌲Redwood, 👍Red Thumb Required 🙏

#3830 Annotate job name with task name
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchJob.scala
Labels: AWS Backend, Back With Originator ♻️

#3867 Better error message for string member accesses
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/types/types.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/types/package.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/linking/expression/package.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/linking/expression/types/EngineFunctionEvaluators.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/linking/expression/types/LookupEvaluators.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/expression/WdlomWomExpression.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/graph/CallElementToGraphNode.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/graph/IfElementToGraphNode.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/graph/ScatterElementToGraphNode.scala
  womtool/src/test/resources/validate/wdl_draft3/invalid/string_member_access/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/string_member_access/string_member_access.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/string_member_access_task/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/string_member_access_task/string_member_access_task.wdl
  womtool/src/test/scala/womtool/WomtoolValidateSpec.scala
Labels: 🌲Redwood

#3875 Fix read_json coercion into Maps
  centaur/src/main/resources/standardTestCases/draft3_read_and_coerce_json.test
  centaur/src/main/resources/standardTestCases/wdl_draft3/draft3_read_and_coerce_json/draft3_read_and_coerce_json.wdl
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/linking/expression/types/LookupEvaluators.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/linking/expression/values/LookupEvaluators.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wdl/WdlWriterImpl.scala
  wom/src/main/scala/wom/types/WomObjectType.scala
Labels: 🌲Redwood

#3913 Use written file to pass correct return code back to Batch
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchJob.scala
  supportedBackends/aws/src/test/scala/cromwell/backend/impl/aws/AwsBatchJobSpec.scala
Labels: AWS Backend

#3914 Add unique host path for storing task data on AWS Batch instances
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchJob.scala
Labels: AWS Backend

#3916 Relatively important
  build.sbt
  centaur/src/main/resources/standardTestCases/biscayne_http_relative_imports.test
  centaur/src/main/resources/standardTestCases/wdl_biscayne/biscayne_http_relative_imports/biscayne_http_relative_imports.wdl
  languageFactories/language-factory-core/src/main/scala/cromwell/languages/util/ImportResolver.scala
  languageFactories/language-factory-core/src/test/scala/cromwell/languages/util/ImportResolverSpec.scala
  languageFactories/wdl-biscayne/src/main/scala/languages/wdl/biscayne/WdlBiscayneLanguageFactory.scala
  languageFactories/wdl-draft2/src/main/scala/languages/wdl/draft2/WdlDraft2LanguageFactory.scala
  languageFactories/wdl-draft3/src/main/scala/languages/wdl/draft3/WdlDraft3LanguageFactory.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/FileElementToWomBundle.scala
  womtool/src/main/scala/womtool/input/WomGraphMaker.scala
  womtool/src/test/resources/validate/biscayne/invalid/bad_task/bad_task.wdl
  womtool/src/test/resources/validate/biscayne/invalid/bad_task/error.txt
  womtool/src/test/resources/validate/biscayne/valid/http_relative_imports/http_relative_imports.wdl
  womtool/src/test/resources/validate/biscayne/valid/relative_imports/relative_imports.wdl
  womtool/src/test/resources/validate/biscayne/valid/relative_imports/structs/my_struct.wdl
  womtool/src/test/resources/validate/biscayne/valid/relative_imports/sub_wfs/foo.wdl
  womtool/src/test/resources/validate/biscayne/valid/relative_imports/sub_wfs/tasks/add5.wdl
Labels: Comply with WDL Spec, 🌲Redwood

#3935 [32] Fix performance issues with concurrent HTTP import validation
  languageFactories/language-factory-core/src/main/scala/cromwell/languages/util/ImportResolver.scala
Labels: HIGH PRIORITY, 👍Red Thumb Required 🙏, 🤕Hotfix Candidate

#3937 [34] Fix performance issues with concurrent HTTP import validation
  languageFactories/language-factory-core/src/main/scala/cromwell/languages/util/ImportResolver.scala
Labels: HIGH PRIORITY, 👍Red Thumb Required 🙏, 🤕Hotfix Candidate

#3915 Initial code for integration with cromwell agent
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchAsyncBackendJobExecutionActor.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchJob.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchJobDefinition.scala
  supportedBackends/aws/src/test/scala/cromwell/backend/impl/aws/AwsBatchJobSpec.scala
Labels: AWS Backend

#3922 Disallow array autoboxing
  CHANGELOG.md
  centaur/src/main/resources/standardTestCases/single_to_array_conversion.test
  centaur/src/main/resources/standardTestCases/single_to_array_conversion/single_to_array_conversion.wdl
  wom/src/main/scala/wom/types/WomArrayType.scala
  wom/src/test/scala/wom/types/WomArrayTypeSpec.scala
  womtool/src/test/resources/validate/wdl_draft2/invalid/array_autoboxing/array_autoboxing.wdl
  womtool/src/test/resources/validate/wdl_draft2/invalid/array_autoboxing/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/array_autoboxing/array_autoboxing.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/array_autoboxing/error.txt
Labels: Comply with WDL Spec, 🌲Redwood

#3936 [33] Fix performance issues with concurrent HTTP import validation
  languageFactories/language-factory-core/src/main/scala/cromwell/languages/util/ImportResolver.scala
Labels: HIGH PRIORITY, 👍Red Thumb Required 🙏, 🤕Hotfix Candidate

#3923 Nicer error message for not-enabled LanguageFactories
  languageFactories/cwl-v1-0/src/main/scala/languages/cwl/CwlV1_0LanguageFactory.scala
  languageFactories/language-factory-core/src/main/scala/cromwell/languages/LanguageFactory.scala
  languageFactories/language-factory-core/src/main/scala/cromwell/languages/StandardLanguageFactoryConfig.scala
  languageFactories/wdl-biscayne/src/main/scala/languages/wdl/biscayne/WdlBiscayneLanguageFactory.scala
  languageFactories/wdl-draft2/src/main/scala/languages/wdl/draft2/WdlDraft2LanguageFactory.scala
  languageFactories/wdl-draft3/src/main/scala/languages/wdl/draft3/WdlDraft3LanguageFactory.scala
Labels: 🌲Redwood
