Repository broadinstitute/cromwell, pull requests merged in 2018-11, with the labels that each got.

#4359 Call cache blacklisting
  CHANGELOG.md
  backend/src/main/scala/cromwell/backend/BackendLifecycleActorFactory.scala
  backend/src/main/scala/cromwell/backend/standard/StandardLifecycleActorFactory.scala
  backend/src/main/scala/cromwell/backend/standard/callcaching/BlacklistCache.scala
  backend/src/main/scala/cromwell/backend/standard/callcaching/StandardCacheHitCopyingActor.scala
  backend/src/test/scala/cromwell/backend/standard/callcaching/BlacklistCacheSpec.scala
  core/src/main/scala/cromwell/core/core.scala
  core/src/main/scala/cromwell/core/io/IoAck.scala
  core/src/main/scala/cromwell/core/io/IoCommand.scala
  cromwell.examples.conf
  docs/cromwell_features/CallCaching.md
  engine/src/main/scala/cromwell/engine/instrumentation/IoInstrumentation.scala
  engine/src/main/scala/cromwell/engine/io/IoActor.scala
  engine/src/main/scala/cromwell/engine/io/gcs/GcsBatchFlow.scala
  engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala
  engine/src/main/scala/cromwell/engine/workflow/WorkflowManagerActor.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/SubWorkflowExecutionActor.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/WorkflowExecutionActor.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/job/EngineJobExecutionActor.scala
  engine/src/test/scala/cromwell/engine/io/gcs/GcsBatchFlowSpec.scala
  engine/src/test/scala/cromwell/engine/workflow/lifecycle/execution/SubWorkflowExecutionActorSpec.scala
  languageFactories/wdl-draft2/src/main/scala/languages/wdl/draft2/WdlDraft2LanguageFactory.scala
  scripts/perf/test_cases/blacklist_call_caching_stress/blacklist_call_caching_stress.test
  scripts/perf/test_cases/blacklist_call_caching_stress/centaur.conf
  scripts/perf/test_cases/blacklist_call_caching_stress/cromwell.conf
  server/src/test/scala/cromwell/SimpleWorkflowActorSpec.scala
  server/src/test/scala/cromwell/engine/workflow/WorkflowActorSpec.scala
  server/src/test/scala/cromwell/engine/workflow/lifecycle/execution/WorkflowExecutionActorSpec.scala
  server/src/test/scala/cromwell/engine/workflow/lifecycle/execution/ejea/PerTestHelper.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/callcaching/PipelinesApiBackendCacheHitCopyingActor.scala
Labels: 📞💵Call Caching

#4283 CWL parsing docs ["from 10,000 feet" edition]
  cwl/src/main/scala/cwl/preprocessor/CwlPreProcessor.scala
  docs/developers/Arch.md
  docs/developers/Building.md
  docs/developers/Centaur.md
  docs/developers/Contribute.md
  docs/developers/CwlParsing.md
  docs/developers/Instrumentation.md
  docs/developers/Security.md
  mkdocs.yml
Labels: 🌲Redwood

#3980 WDL Directory
  centaur/src/main/resources/standardTestCases/directory_type_local.test
  centaur/src/main/resources/standardTestCases/directory_type_papi.test
  centaur/src/main/resources/standardTestCases/wdl_biscayne/directory_type/directory_type.wdl
  centaur/src/main/resources/standardTestCases/wdl_biscayne/directory_type/directory_type_local_inputs.json
  engine/src/main/scala/cromwell/Simpletons.scala
  src/ci/bin/testCentaurTes.sh
  wdl/transforms/biscayne/src/main/java/wdl/biscayne/parser/WdlParser.java
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/ast2wdlom/ast2wdlom.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/ast2wdlom/ast2wdlom.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/AstNodeToTypeElement.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/linking/typemakers/package.scala
  womtool/src/test/resources/validate/biscayne/valid/directory_type/directory_type.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/directory_type/directory_type.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/directory_type/error.txt
  womtool/src/test/resources/validate/wdl_draft3/valid/directory_struct/directory_struct.wdl
Labels: WDL Biscayne, 🌲Redwood

#4308 Allow relative imports from URL-submitted CWL
  centaur/src/main/resources/standardTestCases/cwl_format/cwl_format_url.cwl
  centaur/src/main/resources/standardTestCases/cwl_format_valid_with_workflow_url.test
  centaur/src/main/resources/standardTestCases/cwl_relative_imports_url.test
  centaurCwlRunner/src/main/scala/centaur/cwl/CentaurCwlRunner.scala
  centaurCwlRunner/src/main/scala/centaur/cwl/CloudPreprocessor.scala
  common/src/main/scala/common/validation/Validation.scala
  cwl/src/main/scala/cwl/CwlDecoder.scala
  cwl/src/main/scala/cwl/CwltoolRunner.scala
  cwl/src/main/scala/cwl/preprocessor/CwlCanonicalizer.scala
  cwl/src/main/scala/cwl/preprocessor/CwlPreProcessor.scala
  cwl/src/main/scala/cwl/preprocessor/CwlReference.scala
  cwl/src/test/scala/cwl/CwlDecoderSpec.scala
  cwl/src/test/scala/cwl/preprocessor/CwlPreProcessorSpec.scala
  cwl/src/test/scala/cwl/preprocessor/CwlReferenceSpec.scala
  docs/developers/CwlParsing.md
  languageFactories/cwl-v1-0/src/main/scala/languages/cwl/CwlV1_0LanguageFactory.scala
  server/src/main/scala/cromwell/CommandLineArguments.scala
Labels: 🌲Redwood

#4399 Zip cleanup
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/materialization/MaterializeWorkflowDescriptorActor.scala
  languageFactories/language-factory-core/src/main/scala/cromwell/languages/util/ImportResolver.scala
  languageFactories/language-factory-core/src/main/scala/cromwell/languages/util/LanguageFactoryUtil.scala
  languageFactories/wdl-draft2/src/main/scala/languages/wdl/draft2/WdlDraft2LanguageFactory.scala
Labels: 🌲Redwood, 👍Red Thumb Required 🙏

#4377 add AES256 encryption to copyToS3()
  supportedBackends/aws/src/main/resources/ecs-proxy/proxy
Labels: ⭐ Two Thumbs-Up ⭐

#4378 add missing config options to aws tutorial
  docs/tutorials/AwsBatch101.md
Labels: ⭐ Two Thumbs-Up ⭐

#4402 Synchronize instrumentation with the actor
  engine/src/main/scala/cromwell/engine/workflow/tokens/JobExecutionTokenDispenserActor.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/WorkflowStoreEngineActor.scala
  services/src/main/scala/cromwell/services/instrumentation/CromwellInstrumentation.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/api/PipelinesApiRequestManager.scala
Labels: ⭐ Two Thumbs-Up ⭐

#4401 Database-driven abort.
  CHANGELOG.md
  core/src/main/scala/cromwell/core/abort/AbortResponse.scala
  core/src/main/scala/cromwell/core/core.scala
  cromwell.examples.conf
  database/sql/src/main/scala/cromwell/database/slick/WorkflowStoreSlickDatabase.scala
  database/sql/src/main/scala/cromwell/database/slick/tables/WorkflowStoreEntryComponent.scala
  database/sql/src/main/scala/cromwell/database/sql/WorkflowStoreSqlDatabase.scala
  docs/Configuring.md
  engine/src/main/resources/swagger/cromwell.yaml
  engine/src/main/scala/cromwell/engine/workflow/WorkflowManagerActor.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/AbortRequestScanningActor.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/InMemoryWorkflowStore.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/SqlWorkflowStore.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/WorkflowStore.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/WorkflowStoreActor.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/WorkflowStoreEngineActor.scala
  engine/src/main/scala/cromwell/server/CromwellRootActor.scala
  engine/src/main/scala/cromwell/webservice/routes/CromwellApiService.scala
  engine/src/test/scala/cromwell/engine/workflow/workflowstore/SqlWorkflowStoreSpec.scala
  engine/src/test/scala/cromwell/webservice/routes/CromwellApiServiceSpec.scala
  languageFactories/wdl-draft2/src/main/scala/languages/wdl/draft2/WdlDraft2LanguageFactory.scala
  server/src/test/scala/cromwell/engine/WorkflowStoreActorSpec.scala
Labels: <=== READY FOR REVIEW !!!

#4392 Assert HTTP inputs work in CWL
  CHANGELOG.md
  backend/src/main/scala/cromwell/backend/ReadLikeFunctions.scala
  centaur/src/main/resources/standardTestCases/http_inputs/http_inputs.cwl
  centaur/src/main/resources/standardTestCases/http_inputs/http_inputs.inputs
  centaur/src/main/resources/standardTestCases/http_inputs/http_inputs_cwl.inputs
  centaur/src/main/resources/standardTestCases/http_inputs_cwl.test
  core/src/main/resources/reference.conf
  core/src/main/scala/cromwell/core/path/PathFactory.scala
  docs/filesystems/Filesystems.md
  server/src/test/scala/cromwell/engine/workflow/lifecycle/MaterializeWorkflowDescriptorActorSpec.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/PipelinesApiExpressionFunctions.scala
Labels: <=== READY FOR REVIEW !!!

#4408 Self contained Timing endpoint
  engine/src/main/resources/workflowTimings/workflowTimings.html
  engine/src/main/scala/cromwell/webservice/ApiDataModels.scala
  engine/src/main/scala/cromwell/webservice/routes/CromwellApiService.scala
  engine/src/main/scala/cromwell/webservice/routes/MetadataRouteSupport.scala
  engine/src/test/scala/cromwell/webservice/routes/CromwellApiServiceSpec.scala
Labels: Back With Originator ♻️, ⭐ Two Thumbs-Up ⭐

#4422 Fix typo in docs. Closes #4217
  scripts/docker-develop/README.md
Labels: Back With Originator ♻️, ⭐ Two Thumbs-Up ⭐

#4405 Add new hash path strategy with last modified time
  CHANGELOG.md
  cromwell.examples.conf
  docs/Configuring.md
  supportedBackends/sfs/src/main/scala/cromwell/backend/impl/sfs/config/ConfigHashingStrategy.scala
  supportedBackends/sfs/src/test/scala/cromwell/backend/impl/sfs/config/ConfigHashingStrategySpec.scala
Labels: ⭐ Two Thumbs-Up ⭐

#4396 Prints out the gsutil failures when (de)localizing
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/api/ActionBuilder.scala
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/api/ActionCommands.scala
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/api/Delocalization.scala
  supportedBackends/google/pipelines/v2alpha1/src/test/scala/cromwell/backend/google/pipelines/v2alpha1/api/ActionCommandsSpec.scala
Labels: Back With Originator ♻️, ⭐ Two Thumbs-Up ⭐

#4429 Add a transaction isolation parameter with default, override it in select workflow store spots.
  database/sql/src/main/scala/cromwell/database/slick/SlickDatabase.scala
  database/sql/src/main/scala/cromwell/database/slick/WorkflowStoreSlickDatabase.scala
Labels: Deadlocks 💀🔒, Please re-review now, ⬅️ horicromtal ➡️

#4431 old mock is old and is exercising a dead code path. rejuvinate
  engine/src/main/scala/cromwell/webservice/routes/CromwellApiService.scala
  engine/src/test/scala/cromwell/webservice/routes/CromwellApiServiceSpec.scala
  engine/src/test/scala/cromwell/webservice/routes/wes/WesRouteSupportSpec.scala
Labels: ⭐ Two Thumbs-Up ⭐

#4409 WDL 'keys' function
  centaur/src/main/resources/standardTestCases/biscayne_as_map_et_al.test
  centaur/src/main/resources/standardTestCases/wdl_biscayne/biscayne_as_map_et_al/biscayne_as_map_et_al.wdl
  wdl/model/draft3/src/main/scala/wdl/model/draft3/elements/ExpressionElement.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/ast2wdlom/AstToNewExpressionElements.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/consumed/BiscayneExpressionValueConsumers.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/consumed/consumed.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/files/BiscayneFileEvaluators.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/files/files.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/types/BiscayneTypeEvaluators.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/types/types.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/values/BiscayneValueEvaluators.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/values/values.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/AstToDeclarationContent.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/AstToOutputsSectionElement.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/linking/expression/files/EngineFunctionEvaluators.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wdl/WdlWriterImpl.scala
  womtool/src/test/resources/validate/wdl_draft3/invalid/biscayne_functions/biscayne_functions.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/biscayne_functions/error.txt
Labels: ⭐ Two Thumbs-Up ⭐, 🌲Redwood
