Repository broadinstitute/cromwell, pull requests merged in 2018-05, with the labels that each got.

#3559 Small bundle of new centaur and unit tests for draft 3
  centaur/src/main/resources/standardTestCases/draft3_multiple_sourced_array.test
  centaur/src/main/resources/standardTestCases/draft3_optional_declarations.test
  centaur/src/main/resources/standardTestCases/multiplesourcedarray/multiplesourcedarray.wdl
  centaur/src/main/resources/standardTestCases/unexpected_call_input_failure.test
  centaur/src/main/resources/standardTestCases/unexpected_subworkflow_call_input_failure.test
  centaur/src/main/resources/standardTestCases/wdl_draft3/multiple_sourced_array/multiple_sourced_array.wdl
  centaur/src/main/resources/standardTestCases/wdl_draft3/optional_declarations/optional_declarations.inputs
  centaur/src/main/resources/standardTestCases/wdl_draft3/optional_declarations/optional_declarations.wdl
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/values/LookupEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/CallElementToGraphNode.scala
  womtool/src/test/resources/validate/wdl_draft2/invalid/unexpected_call_input_failure/error.txt
  womtool/src/test/resources/validate/wdl_draft2/invalid/unexpected_call_input_failure/unexpected_call_input_failure.wdl
  womtool/src/test/resources/validate/wdl_draft2/invalid/unexpected_subworkflow_call_input_failure/error.txt
  womtool/src/test/resources/validate/wdl_draft2/invalid/unexpected_subworkflow_call_input_failure/unexpected_subworkflow_call_input_failure.wdl
  womtool/src/test/resources/validate/wdl_draft2/invalid/unexpected_subworkflow_call_input_failure/unexpected_subworkflow_call_input_failure_import.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/unexpected_subworkflow_call_input_failure/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/unexpected_subworkflow_call_input_failure/unexpected_subworkflow_call_input_failure.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/unexpected_subworkflow_call_input_failure/unexpected_subworkflow_call_input_failure_import.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/unwanted_task_input/error.txt
Labels: 🌲Redwood

#3580 Partial Unification Compiler Flag
  .gitignore
  backend/src/main/scala/cromwell/backend/BackendWorkflowInitializationActor.scala
  backend/src/main/scala/cromwell/backend/io/DirectoryFunctions.scala
  backend/src/main/scala/cromwell/backend/io/GlobFunctions.scala
  backend/src/main/scala/cromwell/backend/standard/StandardAsyncExecutionActor.scala
  backend/src/test/scala/cromwell/backend/validation/RuntimeAttributesDefaultSpec.scala
  centaur/src/it/scala/centaur/AbstractCentaurTestCaseSpec.scala
  common/src/test/scala/common/util/TryUtilSpec.scala
  core/src/main/scala/cromwell/core/actor/ThrottlerActor.scala
  core/src/main/scala/cromwell/core/filesystem/CromwellFileSystems.scala
  cwl/src/main/scala/cwl/CommandLineTool.scala
  cwl/src/main/scala/cwl/CommandOutputBinding.scala
  cwl/src/main/scala/cwl/CwlJsonToDelayedCoercionFunction.scala
  cwl/src/main/scala/cwl/CwlType.scala
  cwl/src/main/scala/cwl/InputParameter.scala
  cwl/src/main/scala/cwl/MyriadInputTypeToSortedCommandParts.scala
  cwl/src/main/scala/cwl/MyriadOutputTypeToWomFiles.scala
  cwl/src/main/scala/cwl/MyriadOutputTypeToWomValue.scala
  cwl/src/main/scala/cwl/OutputParameter.scala
  cwl/src/main/scala/cwl/ScatterLogic.scala
  cwl/src/main/scala/cwl/WorkflowStepInputMergeExpression.scala
  cwl/src/main/scala/cwl/internal/CommandPartSortingAlgorithm.scala
  cwl/src/main/scala/cwl/internal/CwlEcmaScriptDecoder.scala
  cwl/src/main/scala/cwl/ontology/Schema.scala
  cwl/src/main/scala/cwl/preprocessor/CwlPreProcessor.scala
  cwl/src/test/scala/cwl/CommandLineToolSpec.scala
  cwl/src/test/scala/cwl/CwlEcmaScriptEncoderSpec.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/WorkflowExecutionActor.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/keys/ScatterKey.scala
  engine/src/main/scala/cromwell/webservice/PartialWorkflowSources.scala
  languageFactories/language-factory-core/src/main/scala/cromwell/languages/util/LanguageFactoryUtil.scala
  project/Settings.scala
  services/src/test/scala/cromwell/services/metadata/impl/MetadataDatabaseAccessSpec.scala
  supportedBackends/sfs/src/test/scala/cromwell/backend/sfs/SharedFileSystemSpec.scala
  wdl/model/draft2/src/test/scala/wdl/WdlWorkflowSpec.scala
  wdl/transforms/draft2/src/main/scala/wdl/transforms/draft2/wdlom2wom/WdlDraft2WomBundleMakers.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/ast2wdlom/EnhancedDraft3Ast.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/package.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/types/LiteralEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/values/EngineFunctionEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/values/LiteralEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/graph/LinkedGraphMaker.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/FileElementToWomBundle.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/TaskDefinitionElementToWomTaskDefinition.scala
  wom/src/main/scala/wom/types/WomCompositeType.scala
  wom/src/main/scala/wom/types/WomObjectType.scala
Labels: 🌲Redwood, 👍Red Thumb Required 🙏

#3605 Adds fixes for a few larger WDLs migrated to 1.0
  centaur/src/main/resources/standardTestCases/draft3_size_of_optionals.test
  centaur/src/main/resources/standardTestCases/wdl_draft3/draft3_size_of_optionals/draft3_size_of_optionals.wdl
  centaur/src/main/resources/standardTestCases/wdl_draft3/draft3_size_of_optionals/size_in_workflow_places.wdl
  languageFactories/language-factory-core/src/main/scala/cromwell/languages/util/ResolvedExecutableInputsPoly.scala
  wdl/model/draft3/src/main/scala/wdl/model/draft3/elements/ExpressionElement.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/ast2wdlom/AstNodeToExpressionElement.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/ast2wdlom/AstToCommandSectionElement.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/types/EngineFunctionEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/graph/package.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/TaskDefinitionElementToWomTaskDefinition.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/expression/renaming/BinaryOperatorEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/expression/renaming/EngineFunctionEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/expression/renaming/IdentifierLookupRenamer.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/expression/renaming/LiteralEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/expression/renaming/LookupEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/expression/renaming/TernaryIfEvaluator.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/expression/renaming/UnaryOperatorEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/expression/renaming/package.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/CallElementToGraphNode.scala
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/wdlom2wom/WdlFileToWomSpec.scala
  womtool/src/test/resources/validate/wdl_draft3/valid/HaplotypeCallerWF/HaplotypeCallerWF.inputs.json
  womtool/src/test/resources/validate/wdl_draft3/valid/HaplotypeCallerWF/HaplotypeCallerWF.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/arrays_v1/arrays_v1.inputs.json
  womtool/src/test/resources/validate/wdl_draft3/valid/arrays_v1/arrays_v1.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/cnv_somatic_pair_workflow/cnv_common_tasks.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/cnv_somatic_pair_workflow/cnv_somatic_oncotator_workflow.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/cnv_somatic_pair_workflow/cnv_somatic_pair_workflow.inputs.json
  womtool/src/test/resources/validate/wdl_draft3/valid/cnv_somatic_pair_workflow/cnv_somatic_pair_workflow.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/joint-discovery-gatk/joint-discovery-gatk.inputs.json
  womtool/src/test/resources/validate/wdl_draft3/valid/joint-discovery-gatk/joint-discovery-gatk.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/multiple_overridable_optionals/multiple_overridable_optionals.inputs.json
  womtool/src/test/resources/validate/wdl_draft3/valid/multiple_overridable_optionals/multiple_overridable_optionals.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/overridable_optionals/overridable_optionals.inputs.json
  womtool/src/test/resources/validate/wdl_draft3/valid/overridable_optionals/overridable_optionals.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/singlesample_v1/singlesample_v1.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/smartseq2_single_sample/HISAT2.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/smartseq2_single_sample/Picard.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/smartseq2_single_sample/RSEM.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/smartseq2_single_sample/smartseq2_single_sample.inputs.json
  womtool/src/test/resources/validate/wdl_draft3/valid/smartseq2_single_sample/smartseq2_single_sample.wdl
Labels: 🌲Redwood, 👍Red Thumb Required 🙏

#3606 A test case for inline python files
  centaur/src/main/resources/standardTestCases/draft3_inline_python.test
  centaur/src/main/resources/standardTestCases/wdl_draft3/draft3_inline_python/draft3_inline_python.inputs.json
  centaur/src/main/resources/standardTestCases/wdl_draft3/draft3_inline_python/draft3_inline_python.wdl
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/InputDeclarationElementToGraphNode.scala
Labels: 🌲Redwood

#3601 WDL 1.0 upgrade script Phase I: WDL writer
  wdl/model/draft3/src/main/scala/wdl/model/draft3/elements/ScatterElement.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/ast2wdlom/AstNodeToTypeElement.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wdl/WdlWriter.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wdl/WdlWriterImpl.scala
  wdl/transforms/draft3/src/test/cases/command_syntaxes.wdl
  wdl/transforms/draft3/src/test/cases/taskless_engine_functions.wdl
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/ast2wdlom/WdlFileToWdlomSpec.scala
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/wdlom2wdl/WdlomToWdlFileSpec.scala
  womtool/src/main/scala/womtool/WomtoolMain.scala
  womtool/src/main/scala/womtool/cmdline/PartialWomtoolCommandLineArguments.scala
  womtool/src/main/scala/womtool/cmdline/WomtoolCommandLineParser.scala
Labels: 🌲Redwood, 👍Red Thumb Required 🙏

#3611 Added input generation (and tests) for WDL 1.0 and CWL
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/expression/WdlomWomExpression.scala
  womtool/src/main/scala/womtool/WomtoolMain.scala
  womtool/src/main/scala/womtool/cmdline/PartialWomtoolCommandLineArguments.scala
  womtool/src/main/scala/womtool/cmdline/WomtoolCommandLineParser.scala
  womtool/src/main/scala/womtool/inputs/Inputs.scala
  womtool/src/test/resources/inputs/wdl_draft2/needs_an_input/all.inputs.json
  womtool/src/test/resources/inputs/wdl_draft2/needs_an_input/required.inputs.json
  womtool/src/test/resources/inputs/wdl_draft2/scatter/all.inputs.json
  womtool/src/test/resources/inputs/wdl_draft2/scatter/required.inputs.json
  womtool/src/test/resources/inputs/wdl_draft2/subworkflow_input/all.inputs.json
  womtool/src/test/resources/inputs/wdl_draft2/subworkflow_input/required.inputs.json
  womtool/src/test/resources/inputs/wdl_draft2/three_step/all.inputs.json
  womtool/src/test/resources/inputs/wdl_draft2/three_step/required.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/HaplotypeCallerWF/all.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/HaplotypeCallerWF/required.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/arrays_v1/all.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/arrays_v1/required.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/callable_imports/all.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/callable_imports/required.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/cnv_somatic_pair_workflow/all.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/cnv_somatic_pair_workflow/required.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/joint-discovery-gatk/all.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/joint-discovery-gatk/required.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/multiple_overridable_optionals/all.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/multiple_overridable_optionals/required.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/needs_an_input/all.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/needs_an_input/required.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/nested_imports_with_input/all.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/nested_imports_with_input/required.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/overridable_optionals/all.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/overridable_optionals/required.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/singlesample_v1/all.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/singlesample_v1/required.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/smartseq2_single_sample/all.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/smartseq2_single_sample/required.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/subworkflow_input/all.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/subworkflow_input/required.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/three_step/all.inputs.json
  womtool/src/test/resources/inputs/wdl_draft3/three_step/required.inputs.json
  womtool/src/test/scala/womtool/WomtoolInputsSpec.scala
  womtool/src/test/scala/womtool/WomtoolMainSpec.scala
Labels: 🌲Redwood

#3628 Fixes to allow the 1.0 GOTC single sample pipeline to complete
  backend/src/main/scala/cromwell/backend/BackendJobExecutionActor.scala
  backend/src/main/scala/cromwell/backend/async/AsyncBackendJobExecutionActor.scala
  backend/src/main/scala/cromwell/backend/standard/callcaching/StandardCacheHitCopyingActor.scala
  backend/src/test/scala/cromwell/backend/BackendSpec.scala
  centaur/src/main/resources/standardTestCases/draft3_nested_scatter.test
  centaur/src/main/resources/standardTestCases/draft3_optional_addition.test
  centaur/src/main/resources/standardTestCases/missing_input_failure.test
  centaur/src/main/resources/standardTestCases/wdl_draft3/draft3_optional_addition/draft3_optional_addition.wdl
  centaur/src/main/resources/standardTestCases/wdl_draft3/nested_scatter/nested_scatter.wdl
  centaur/src/main/resources/standardTestCases/wdl_draft3/sizeenginefunction/sizeenginefunction.wdl
  common/src/main/scala/common/validation/Validation.scala
  docs/api/RESTAPI.md
  engine/src/main/resources/swagger/cromwell.yaml
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/WorkflowExecutionActor.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/callcaching/CallCache.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/job/EngineJobExecutionActor.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/keys/ConditionalKey.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/keys/ExpressionKey.scala
  engine/src/main/scala/cromwell/jobstore/jobstore_.scala
  engine/src/test/scala/cromwell/engine/backend/mock/DefaultBackendJobExecutionActor.scala
  server/src/test/scala/cromwell/engine/workflow/lifecycle/execution/ejea/EngineJobExecutionActorSpecUtil.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/api/PipelinesApiRequestManager.scala
  supportedBackends/sfs/src/test/scala/cromwell/backend/sfs/SharedFileSystemJobExecutionActorSpec.scala
  supportedBackends/spark/src/main/scala/cromwell/backend/impl/spark/SparkJobExecutionActor.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/values/BinaryOperatorEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/FileElementToWomBundle.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/TaskDefinitionElementToWomTaskDefinition.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/WorkflowDefinitionElementToWomWorkflowDefinition.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/CallElementToGraphNode.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/IfElementToGraphNode.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/InputDeclarationElementToGraphNode.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/renaming/GraphIdentifierLookupRenamer.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/renaming/package.scala
  womtool/src/main/scala/womtool/WomtoolMain.scala
  womtool/src/test/resources/validate/wdl_draft3/invalid/unexpected_subworkflow_call_input_failure/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/unwanted_task_input/error.txt
  womtool/src/test/resources/validate/wdl_draft3/valid/supplied_subworkflow_inputs/subworkflow.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/supplied_subworkflow_inputs/supplied_subworkflow_inputs.wdl
Labels: 🌲Redwood

#3640 Catch sub-workflow task input passing from inputs.json at validation time.
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/CallElementToGraphNode.scala
  womtool/src/test/resources/validate/wdl_draft3/invalid/subwf_sub_inputs/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/subwf_sub_inputs/import_me.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/subwf_sub_inputs/subwf_sub_inputs.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/supplied_optional_subwf_sub_inputs/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/supplied_optional_subwf_sub_inputs/import_me.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/supplied_optional_subwf_sub_inputs/supplied_optional_subwf_sub_inputs.inputs.json
  womtool/src/test/resources/validate/wdl_draft3/invalid/supplied_optional_subwf_sub_inputs/supplied_optional_subwf_sub_inputs.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/subwf_sub_inputs/import_me.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/subwf_sub_inputs/subwf_sub_inputs.wdl
Labels: 🌲Redwood

#3659 1.0: default workflow outputs
  centaur/src/main/resources/standardTestCases/draft3_omitting_outputs.test
  centaur/src/main/resources/standardTestCases/wdl_draft3/draft3_omitting_outputs/draft3_omitting_outputs.wdl
  centaur/src/main/resources/standardTestCases/wdl_draft3/draft3_omitting_outputs/import_me.wdl
  wdl/model/draft2/src/main/scala/wdl/draft2/model/WorkflowOutput.scala
  wdl/transforms/draft2/src/main/scala/wdl/transforms/draft2/wdlom2wom/WdlDraft2WomGraphMaker.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/WorkflowDefinitionElementToWomWorkflowDefinition.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/CallElementToGraphNode.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/IfElementToGraphNode.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/ScatterElementToGraphNode.scala
  wdl/transforms/shared/src/main/scala/wdl/shared/transforms/wdlom2wom/WomGraphMakerTools.scala
  womtool/src/test/resources/validate/wdl_draft3/invalid/importing_omitting_outputs/draft3_omitting_outputs.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/importing_omitting_outputs/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/importing_omitting_outputs/import_me.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/importing_omitting_outputs/importing_omitting_outputs.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/supplied_optional_subwf_sub_inputs/import_me.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/subwf_sub_inputs/import_me.wdl
Labels: 🌲Redwood

#3653 Call cache capoeira for 1.0 (plus ensure task hashes match draft-2)
  centaur/src/main/resources/standardTestCases/draft3_call_cache_capoeira_jes.test
  centaur/src/main/resources/standardTestCases/draft3_call_cache_capoeira_local.test
  centaur/src/main/resources/standardTestCases/draft3_call_cache_capoeira_tes.test
  centaur/src/main/resources/standardTestCases/draft3_write_lines.test
  centaur/src/main/resources/standardTestCases/draft3_write_lines_files.test
  centaur/src/main/resources/standardTestCases/wdl_draft3/call_cache_capoeira/draft3_call_cache_capoeira_jes.wdl
  centaur/src/main/resources/standardTestCases/wdl_draft3/call_cache_capoeira/draft3_call_cache_capoeira_local.wdl
  centaur/src/main/resources/standardTestCases/wdl_draft3/call_cache_capoeira/draft3_call_cache_capoeira_tes.wdl
  centaur/src/main/resources/standardTestCases/wdl_draft3/draft3_write_lines/draft3_write_lines.wdl
  centaur/src/main/resources/standardTestCases/wdl_draft3/draft3_write_lines_files/draft3_write_lines_files.wdl
  src/bin/ci/testCentaurTes.sh
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wdl/WdlWriterImpl.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/CommandPartElementToWomCommandPart.scala
Labels: 🌲Redwood, 👍Red Thumb Required 🙏

#3676 Language and Version inference
  centaur/src/main/resources/standardTestCases/cwl_optionals.test
  centaur/src/main/resources/standardTestCases/draft3_infer_version.test
  centaur/src/main/resources/standardTestCases/forkjoin.test
  centaur/src/main/resources/standardTestCases/wdl_draft3/draft3_infer_version/draft3_infer_version.wdl
  centaur/src/main/resources/standardTestCases/workflow_type_and_version_default.test
  centaur/src/main/resources/standardTestCases/workflow_type_and_version_default/workflow_type_and_version_default.wdl
  core/src/main/resources/reference.conf
  core/src/main/scala/cromwell/core/WorkflowMetadataKeys.scala
  core/src/main/scala/cromwell/core/WorkflowOptions.scala
  engine/src/main/scala/cromwell/engine/language/CromwellLanguages.scala
  engine/src/main/scala/cromwell/engine/language/LanguageConfiguration.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/materialization/MaterializeWorkflowDescriptorActor.scala
  engine/src/main/scala/cromwell/webservice/PartialWorkflowSources.scala
  languageFactories/cwl-v1-0/src/main/scala/languages/cwl/CwlV1_0LanguageFactory.scala
  languageFactories/language-factory-core/src/main/scala/cromwell/languages/LanguageFactory.scala
  languageFactories/wdl-draft2/src/main/scala/languages/wdl/draft2/WdlDraft2LanguageFactory.scala
  languageFactories/wdl-draft3/src/main/scala/languages/wdl/draft3/WdlDraft3LanguageFactory.scala
  server/src/main/scala/cromwell/CommandLineArguments.scala
Labels: 🌲Redwood, 👍Red Thumb Required 🙏

#3685 Wire through HTTP resolver for WDL 1.0
  build.sbt
  centaur/src/main/resources/standardTestCases/draft3_http_imports.test
  centaur/src/main/resources/standardTestCases/wdl_draft3/draft3_http_imports/draft3_http_imports.wdl
  languageFactories/language-factory-core/src/main/scala/cromwell/languages/util/ImportResolver.scala
  languageFactories/wdl-draft2/src/main/scala/languages/wdl/draft2/WdlDraft2LanguageFactory.scala
  languageFactories/wdl-draft2/src/test/scala/languages.wdl.draft2/WdlWorkflowHttpImportSpec.scala
  languageFactories/wdl-draft3/src/main/scala/languages/wdl/draft3/WdlDraft3LanguageFactory.scala
  project/Dependencies.scala
  wdl/model/draft2/src/main/scala/wdl/draft2/model/WdlNamespace.scala
Labels: 🌲Redwood, 👍Red Thumb Required 🙏

#3692 Disable requester pays
  CHANGELOG.md
  centaur/src/main/resources/standardTestCases/globbing_behavior_with_requester_pays.test
  centaur/src/main/resources/standardTestCases/input_from_bucket_with_requester_pays.test
  centaur/src/main/resources/standardTestCases/missing_input_failure.test
  centaur/src/main/resources/standardTestCases/read_file_from_bucket_with_requester_pays.test
  docs/backends/Google.md
  filesystems/gcs/src/main/scala/cromwell/filesystems/gcs/GcsPathBuilder.scala
  filesystems/gcs/src/main/scala/cromwell/filesystems/gcs/batch/GcsBatchIoCommand.scala
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/PipelinesConversions.scala
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/api/ActionBuilder.scala
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/api/Delocalization.scala
Labels: 🚧BLOCKS RELEASE🚧
