Repository broadinstitute/cromwell, pull requests merged in 2018-08, with the labels that each got.

#3938 Even More Important
  common/src/main/scala/common/util/IntrospectableLazy.scala
  common/src/test/scala/common/util/IntrospectableLazySpec.scala
  engine/src/main/scala/cromwell/server/CromwellShutdown.scala
  languageFactories/language-factory-core/src/main/scala/cromwell/languages/util/ImportResolver.scala
  womtool/src/main/scala/womtool/WomtoolMain.scala
Labels: Please re-review now

#3949 Interpolate optionals using a default 'default=""'
  centaur/src/main/resources/standardTestCases/default_default.test
  centaur/src/main/resources/standardTestCases/wdl_biscayne/default_default/default_default.wdl
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/CommandPartElementToWomCommandPart.scala
Labels: Comply with WDL Spec, 🌲Redwood

#3925 Import support in womtool upgrade
  centaur/src/it/scala/centaur/AbstractCentaurTestCaseSpec.scala
  centaur/src/main/resources/standardTestCases/sub_workflow_hello_world.test
  centaur/src/main/resources/standardTestCases/sub_workflow_var_refs.test
  centaur/src/main/resources/standardTestCases/sub_workflow_var_refs/sub_workflow_var_refs.wdl
  wdl/transforms/draft2/src/main/scala/wdl/transforms/draft2/wdlom2wom/WdlDraft2WomCommandTaskDefinitionMaker.scala
  wdl/transforms/draft2/src/main/scala/wdl/transforms/draft2/wdlom2wom/WdlDraft2WomWorkflowDefinitionMaker.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wdl/WdlWriterImpl.scala
  womtool/src/main/scala/womtool/WomtoolMain.scala
  womtool/src/main/scala/womtool/cmdline/WomtoolCommandLineParser.scala
  womtool/src/main/scala/womtool/wom2wdlom/WomToWdlom.scala
Labels: 🌲Redwood

#3965 Reduce hash cost of WdlSyntaxErrorFormatter
  wdl/model/draft2/src/main/scala/wdl/draft2/model/WdlSyntaxErrorFormatter.scala
Labels: 🐛Bug

#3946 JES Localization Command
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/api/ActionCommands.scala
  supportedBackends/google/pipelines/v2alpha1/src/test/scala/cromwell/backend/google/pipelines/v2alpha1/api/ActionCommandsSpec.scala
Labels: Back With Originator ♻️

#3934 Cromwell agent
  supportedBackends/aws/src/main/resources/agent/Dockerfile
  supportedBackends/aws/src/main/resources/agent/build-agent
  supportedBackends/aws/src/main/resources/agent/launch_sidecar
  supportedBackends/aws/src/main/resources/agent/monitor
  supportedBackends/aws/src/main/resources/agent/run-agent
  supportedBackends/aws/src/main/resources/agent/spawnoninput.go
Labels: AWS Backend

#3978 Allow FetchCachedResultsActor to complete if post-processing fails
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/callcaching/FetchCachedResultsActor.scala
Labels: 🐛Bug

#3971 WDL Draft 2 workflow source + imports => namespace cache
  CHANGELOG.md
  cromwell.examples.conf
  engine/src/main/scala/cromwell/engine/language/CromwellLanguages.scala
  engine/src/main/scala/cromwell/engine/language/LanguageConfiguration.scala
  languageFactories/cwl-v1-0/src/main/scala/languages/cwl/CwlV1_0LanguageFactory.scala
  languageFactories/language-factory-core/src/main/scala/cromwell/languages/LanguageFactory.scala
  languageFactories/language-factory-core/src/main/scala/cromwell/languages/StandardLanguageFactoryConfig.scala
  languageFactories/wdl-biscayne/src/main/scala/languages/wdl/biscayne/WdlBiscayneLanguageFactory.scala
  languageFactories/wdl-draft2/src/main/scala/languages/wdl/draft2/WdlDraft2LanguageFactory.scala
  languageFactories/wdl-draft2/src/test/scala/languages.wdl.draft2/NamespaceCacheSpec.scala
  languageFactories/wdl-draft2/src/test/scala/languages.wdl.draft2/WdlWorkflowHttpImportSpec.scala
  languageFactories/wdl-draft3/src/main/scala/languages/wdl/draft3/WdlDraft3LanguageFactory.scala
  womtool/src/main/scala/womtool/input/WomGraphMaker.scala
Labels: Back With Originator ♻️

#4033 Fix metadata, call caching issues for CWL Long type
  centaur/src/main/resources/standardTestCases/cwl_cache_between_workflows/cwl_cache_between_workflows.cwl
  engine/src/main/scala/cromwell/Simpletons.scala
  services/src/main/scala/cromwell/services/metadata/MetadataQuery.scala
Labels: CWL, 🌲Redwood, 👍Red Thumb Required 🙏

#3987 Better import failure messages and importLocalFilesystem resolver set
  centaur/src/main/resources/standardTestCases/import_passwd.test
  centaur/src/main/resources/standardTestCases/import_passwd/import_passwd.wdl
  centaur/src/main/resources/standardTestCases/invalid_workflow_url.test
  common/src/main/scala/common/validation/Validation.scala
  engine/src/main/scala/cromwell/engine/workflow/SingleWorkflowRunnerActor.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/materialization/MaterializeWorkflowDescriptorActor.scala
  engine/src/main/scala/cromwell/server/CromwellRootActor.scala
  engine/src/main/scala/cromwell/server/CromwellServer.scala
  languageFactories/language-factory-core/src/main/scala/cromwell/languages/util/ImportResolver.scala
  languageFactories/language-factory-core/src/test/scala/cromwell/languages/util/ImportResolverSpec.scala
  server/src/test/scala/cromwell/CromwellTestKitSpec.scala
  server/src/test/scala/cromwell/engine/workflow/lifecycle/MaterializeWorkflowDescriptorActorSpec.scala
  womtool/src/main/scala/womtool/input/WomGraphMaker.scala
  womtool/src/test/resources/validate/wdl_draft3/invalid/bad_import/bad_import.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/bad_import/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/bad_import/sub_dir/bad_import.wdl
Labels: 🌲Redwood

#3991 Add regression tests for nonexistent local imports.
  womtool/src/test/resources/validate/wdl_draft2/invalid/bad_local_import/bad_local_import.wdl
  womtool/src/test/resources/validate/wdl_draft2/invalid/bad_local_import/error.txt
Labels: 🌲Redwood

#3970 Verify read_json works with "empty string" values
  centaur/src/main/resources/standardTestCases/cwl_format_invalid.test
  centaur/src/main/resources/standardTestCases/draft3_read_write_functions_local.test
  centaur/src/main/resources/standardTestCases/draft3_read_write_functions_papi.test
  centaur/src/main/resources/standardTestCases/read_write_json/read_write_json.wdl
  centaur/src/main/resources/standardTestCases/wdl_draft3/read_write_functions/read_write_functions.wdl
  src/ci/bin/testCentaurTes.sh
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/linking/expression/values/EngineFunctionEvaluators.scala
  wom/src/main/scala/wom/graph/CallNode.scala
Labels: Comply with WDL Spec, 🌲Redwood

#3996 Catch other message type when cache copy fails
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/job/EngineJobExecutionActor.scala
  server/src/test/scala/cromwell/engine/workflow/lifecycle/execution/ejea/EjeaFetchingCachedOutputsFromDatabaseSpec.scala
Labels: 🤕Hotfix Candidate

#4019 Execution bucket call caching hint support.
  CHANGELOG.md
  backend/src/main/scala/cromwell/backend/io/WorkflowPaths.scala
  centaur/src/main/resources/standardTestCases/call_cache_hit_prefixes/call_cache_hit_prefixes.wdl
  centaur/src/main/resources/standardTestCases/call_cache_hit_prefixes/call_cache_hit_prefixes_empty_hint.inputs
  centaur/src/main/resources/standardTestCases/call_cache_hit_prefixes/call_cache_hit_prefixes_empty_hint.options
  centaur/src/main/resources/standardTestCases/call_cache_hit_prefixes/call_cache_hit_prefixes_no_hint.inputs
  centaur/src/main/resources/standardTestCases/call_cache_hit_prefixes/call_cache_hit_prefixes_two_roots_empty_hint_papi.inputs
  centaur/src/main/resources/standardTestCases/call_cache_hit_prefixes/call_cache_hit_prefixes_two_roots_empty_hint_papi_first.options
  centaur/src/main/resources/standardTestCases/call_cache_hit_prefixes/call_cache_hit_prefixes_two_roots_empty_hint_papi_second.options
  centaur/src/main/resources/standardTestCases/call_cache_hit_prefixes_empty_hint_local.test
  centaur/src/main/resources/standardTestCases/call_cache_hit_prefixes_empty_hint_papi.test
  centaur/src/main/resources/standardTestCases/call_cache_hit_prefixes_no_hint.test
  centaur/src/main/resources/standardTestCases/call_cache_hit_prefixes_two_roots_empty_hint_papi.test
  centaur/src/main/scala/centaur/test/formulas/TestFormulas.scala
  centaur/src/main/scala/centaur/test/workflow/Workflow.scala
  centaur/src/main/scala/centaur/test/workflow/WorkflowData.scala
  core/src/main/scala/cromwell/core/WorkflowOptions.scala
  core/src/main/scala/cromwell/core/callcaching/CallCachingMode.scala
  database/sql/src/main/scala/cromwell/database/slick/CallCachingSlickDatabase.scala
  database/sql/src/main/scala/cromwell/database/slick/tables/CallCachingAggregationEntryComponent.scala
  database/sql/src/main/scala/cromwell/database/sql/CallCachingSqlDatabase.scala
  docs/CallCaching.md
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/callcaching/CallCache.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/callcaching/CallCacheHashingJobActor.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/callcaching/CallCacheReadActor.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/callcaching/CallCacheReadingJobActor.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/callcaching/EngineJobHashingActor.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/materialization/MaterializeWorkflowDescriptorActor.scala
  engine/src/test/scala/cromwell/engine/workflow/lifecycle/execution/callcaching/CallCacheHashingJobActorSpec.scala
  engine/src/test/scala/cromwell/engine/workflow/lifecycle/execution/callcaching/CallCacheReadingJobActorSpec.scala
  engine/src/test/scala/cromwell/engine/workflow/lifecycle/execution/callcaching/EngineJobHashingActorSpec.scala
  server/src/test/scala/cromwell/engine/workflow/lifecycle/execution/ejea/EjeaBackendIsCopyingCachedOutputsSpec.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/PipelinesApiWorkflowPaths.scala
  supportedBackends/google/pipelines/common/src/test/scala/cromwell/backend/google/pipelines/common/PipelinesApiAsyncBackendJobExecutionActorSpec.scala
  supportedBackends/google/pipelines/common/src/test/scala/cromwell/backend/google/pipelines/common/PipelinesApiAttributesSpec.scala
  supportedBackends/google/pipelines/common/src/test/scala/cromwell/backend/google/pipelines/common/PipelinesApiCallPathsSpec.scala
  supportedBackends/google/pipelines/common/src/test/scala/cromwell/backend/google/pipelines/common/PipelinesApiConfigurationSpec.scala
  supportedBackends/google/pipelines/common/src/test/scala/cromwell/backend/google/pipelines/common/PipelinesApiInitializationActorSpec.scala
  supportedBackends/google/pipelines/common/src/test/scala/cromwell/backend/google/pipelines/common/PipelinesApiRuntimeAttributesSpec.scala
  supportedBackends/google/pipelines/common/src/test/scala/cromwell/backend/google/pipelines/common/PipelinesApiTestConfig.scala
  supportedBackends/google/pipelines/common/src/test/scala/cromwell/backend/google/pipelines/common/PipelinesApiWorkflowPathsSpec.scala
  supportedBackends/google/pipelines/common/src/test/scala/cromwell/backend/google/pipelines/common/api/PipelinesApiRequestManagerSpec.scala
  supportedBackends/google/pipelines/v1alpha2/src/test/scala/cromwell/backend/google/pipelines/v1alpha2/api/PipelinesApiRequestWorkerV1Spec.scala
Labels: Please re-review now, Resiliency
