Repository broadinstitute/cromwell, pull requests merged in 2018-06, with the labels that each got.

#3729 correct reference to papi config in workbench health actor
  services/src/main/scala/cromwell/services/healthmonitor/impl/workbench/WorkbenchHealthMonitorServiceActor.scala
Labels: ⛔ DO NOT MERGE ⛔

#3725 Quotation marks when quoting source in error msg
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/parsing/WdlDraft3SyntaxErrorFormatter.scala
  womtool/src/test/resources/validate/wdl_draft3/invalid/missing_equal/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/missing_equal/missing_equal.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/missing_identifier/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/missing_identifier/missing_identifier.wdl
Labels: 🌲Redwood, 👍Red Thumb Required 🙏

#3763 Fix member access on scatter variables
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/graph/package.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/ScatterElementToGraphNode.scala
  wdl/transforms/draft3/src/test/cases/scatter_var_member_access.wdl
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/wdlom2wom/WdlFileToWomSpec.scala
Labels: Comply with WDL Spec, 🌲Redwood

#3764 Fix new test case
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/ast2wdlom/WdlFileToWdlomSpec.scala
Labels: 🌲Redwood

#3768 Prevent nested if-statements from creating nested optionals
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/graph/package.scala
  wdl/transforms/draft3/src/test/cases/nested_conditionals.wdl
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/ast2wdlom/WdlFileToWdlomSpec.scala
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/wdlom2wom/WdlFileToWomSpec.scala
Labels: Comply with WDL Spec, 🌲Redwood

#3738 NIO parameter_meta flag for localization optimization
  CHANGELOG.md
  backend/src/main/scala/cromwell/backend/backend.scala
  backend/src/main/scala/cromwell/backend/standard/StandardAsyncExecutionActor.scala
  centaur/src/main/resources/standardTestCases/draft3_nio_file.test
  centaur/src/main/resources/standardTestCases/wdl_draft3/draft3_nio_file/draft3_nio_file.wdl
  cwl/src/main/scala/cwl/WorkflowStep.scala
  docs/optimizations/FileLocalization.md
  docs/optimizations/optimizations.md
  mkdocs.yml
  supportedBackends/aws/src/test/scala/cromwell/backend/impl/aws/AwsBatchAsyncBackendJobExecutionActorSpec.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/PipelinesApiAsyncBackendJobExecutionActor.scala
  supportedBackends/google/pipelines/common/src/test/scala/cromwell/backend/google/pipelines/common/PipelinesApiAsyncBackendJobExecutionActorSpec.scala
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/PipelinesApiAsyncBackendJobExecutionActor.scala
  supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystem.scala
  wdl/model/draft2/src/main/scala/wdl/draft2/model/Declaration.scala
  wdl/model/draft3/src/main/scala/wdl/model/draft3/elements/MetaSectionElement.scala
  wdl/model/draft3/src/main/scala/wdl/model/draft3/elements/ParameterMetaSectionElement.scala
  wdl/transforms/draft2/src/main/scala/wdl/transforms/draft2/wdlom2wom/WdlDraft2WomCallNodeMaker.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/ast2wdlom/AstNodeToMetaKvPair.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/ast2wdlom/AstNodeToMetaValueElement.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/ast2wdlom/AstToMetaSectionElement.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/ast2wdlom/AstToParameterMetaSectionElement.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/ast2wdlom/AstToTaskDefinitionElement.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/ast2wdlom/package.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/files/EngineFunctionEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wdl/WdlWriterImpl.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/TaskDefinitionElementToWomTaskDefinition.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/CallElementToGraphNode.scala
  wdl/transforms/draft3/src/test/cases/nio_file.wdl
  wdl/transforms/draft3/src/test/cases/task_with_metas.nowom.wdl
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/ast2wdlom/WdlFileToWdlomSpec.scala
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/wdlom2wom/WdlFileToWomSpec.scala
  wom/src/main/scala/wom/WomFileMapper.scala
  wom/src/main/scala/wom/callable/Callable.scala
  wom/src/main/scala/wom/callable/MetaValueElement.scala
  wom/src/main/scala/wom/expression/InputPointerToWomValue.scala
  wom/src/main/scala/wom/graph/CallNode.scala
  womtool/src/test/resources/inputs/wdl_draft3/smartseq2_single_sample/all.inputs.json
  womtool/src/test/resources/validate/wdl_draft3/valid/smartseq2_single_sample/HISAT2.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/smartseq2_single_sample/Picard.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/smartseq2_single_sample/RSEM.wdl
  womtool/src/test/scala/womtool/WomtoolInputsSpec.scala
Labels: 🌲Redwood

#3772 Allow task-only validation in draft 2 WDL
  languageFactories/wdl-draft2/src/main/scala/languages/wdl/draft2/WdlDraft2LanguageFactory.scala
  wdl/transforms/draft2/src/main/scala/wdl/transforms/draft2/wdlom2wom/WdlDraft2WomBundleMakers.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/FileElementToWomBundle.scala
  womtool/src/main/scala/womtool/input/WomGraphMaker.scala
  womtool/src/main/scala/womtool/validate/Validate.scala
  womtool/src/test/resources/validate/wdl_draft2/valid/task_only/task_only.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/task_only/task_only.wdl
  womtool/src/test/scala/womtool/WomtoolMainSpec.scala
Labels: 🌲Redwood, 👍Red Thumb Required 🙏

#3771 Extend localization_optional to complex types (for least surprise)
  backend/src/main/scala/cromwell/backend/backend.scala
  centaur/src/main/resources/standardTestCases/draft3_nio_file.test
  centaur/src/main/resources/standardTestCases/wdl_draft3/draft3_nio_file/draft3_nio_file.wdl
  docs/optimizations/FileLocalization.md
Labels: 🌲Redwood

#3783 Re-allow expression short-circuiting in WDL 1.0
  centaur/src/main/resources/standardTestCases/draft3_short_circuit.test
  centaur/src/main/resources/standardTestCases/wdl_draft3/draft3_short_circuit/draft3_short_circuit.wdl
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/values/BinaryOperatorEvaluators.scala
Labels: 🌲Redwood

#3788 Add Cromwell versioning note for localization_optional
  docs/optimizations/FileLocalization.md
Labels: 👍Red Thumb Required 🙏

#3775 Optional inputs from scatter
  centaur/src/main/resources/standardTestCases/draft3_optional_input_from_scatter.test
  centaur/src/main/resources/standardTestCases/wdl_draft3/draft3_optional_input_from_scatter/draft3_optional_input_from_scatter.inputs.json
  centaur/src/main/resources/standardTestCases/wdl_draft3/draft3_optional_input_from_scatter/draft3_optional_input_from_scatter.wdl
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/ScatterElementToGraphNode.scala
  womtool/src/test/resources/validate/wdl_draft3/valid/optional_input_from_scatter/optional_input_from_scatter.inputs.json
  womtool/src/test/resources/validate/wdl_draft3/valid/optional_input_from_scatter/optional_input_from_scatter.wdl
Labels: 🌲Redwood

#3777 Validate variable lookups in draft 2 runtime attributes
  wdl/model/draft2/src/main/scala/wdl/draft2/model/WdlNamespace.scala
  wdl/model/draft3/src/main/scala/wdl/model/draft3/graph/UnlinkedConsumedValueHook.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/graph/LinkedGraphMaker.scala
  womtool/src/test/resources/validate/wdl_draft2/invalid/bad_task/bad_task.wdl
  womtool/src/test/resources/validate/wdl_draft2/invalid/bad_task/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/bad_task/bad_task.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/bad_task/error.txt
Labels: 🌲Redwood, 👍Red Thumb Required 🙏

#3794 Allow conditionals and scatters based on 'WomAnyType' values
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/IfElementToGraphNode.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/ScatterElementToGraphNode.scala
  womtool/src/test/resources/validate/wdl_draft3/valid/member_access_types/member_access_types.wdl
Labels: 🌲Redwood, 👍Red Thumb Required 🙏

#3812 Fix CPU coercion in SFS backend
  supportedBackends/sfs/src/main/scala/cromwell/backend/impl/sfs/config/CpuDeclarationValidation.scala
  supportedBackends/sfs/src/main/scala/cromwell/backend/impl/sfs/config/DeclarationValidation.scala
  supportedBackends/sfs/src/test/scala/cromwell/backend/sfs/config/DeclarationValidationSpec.scala
Labels: 🚧BLOCKS RELEASE🚧

#3803 fix tempdir examples
  cromwell.examples.conf
Labels: 🚧BLOCKS RELEASE🚧
