Repository broadinstitute/cromwell, pull requests merged in 2018-10, with the labels that each got.

#4190 Fix CWL "failed with null" error message
  cwl/src/main/scala/cwl/CwlDecoder.scala
  cwl/src/test/scala/cwl/CwlDecoderSpec.scala
Labels: CWL, User Joy 😄, 🌲Redwood

#4262 Better message for bad path
  core/src/main/scala/cromwell/core/path/PathFactory.scala
  filesystems/gcs/src/main/scala/cromwell/filesystems/gcs/GcsPathBuilder.scala
  filesystems/gcs/src/test/scala/cromwell/filesystems/gcs/GcsPathBuilderSpec.scala
  supportedBackends/aws/src/test/scala/cromwell/backend/impl/aws/AwsBatchJobSpec.scala
Labels: User Joy 😄

#4264 add encyrption to s3 file transfers via ecs-proxy
  supportedBackends/aws/src/main/resources/ecs-proxy/proxy
Labels: AWS Backend

#4244 Add a test for CWL relative imports using zips
  centaur/src/main/resources/standardTestCases/cwl_relative_imports/cwl_glob_sort.cwl
  centaur/src/main/resources/standardTestCases/cwl_relative_imports/workflow.cwl
  centaur/src/main/resources/standardTestCases/cwl_relative_imports_zip.test
  cwl/src/main/scala/cwl/CwlDecoder.scala
Labels: 🌲Redwood

#4261 Export Span Scale factor to sbt for Jenkins
  project/Testing.scala
  src/ci/bin/test.inc.sh
  src/ci/bin/testSbt.sh
Labels: Please re-review now

#4267 Scale the HMSASpec ask timeout for jenkins.
  services/src/test/scala/cromwell/services/healthmonitor/HealthMonitorServiceActorSpec.scala
Labels: Back With Originator ♻️

#4270 Small changes to release WDL
  release/release_workflow.wdl
Labels: 🌲Redwood

#4324 Fix type compatibility regression on empty arrays
  CHANGELOG.md
  wom/src/main/scala/wom/types/WomType.scala
  wom/src/test/scala/wom/types/WomTypeSpec.scala
Labels: User Joy 😄, 🌲Redwood
