Repository broadinstitute/cromwell, pull requests merged in 2018-09, with the labels that each got.

#4071 Count subworkflows against the max concurrent workflows limit.
  core/src/test/scala/cromwell/util/SampleWdl.scala
  engine/src/main/scala/cromwell/engine/engine.scala
  engine/src/main/scala/cromwell/engine/workflow/WorkflowManagerActor.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/SubWorkflowExecutionActor.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/InMemorySubWorkflowStore.scala
  engine/src/main/scala/cromwell/server/CromwellRootActor.scala
  server/src/test/scala/cromwell/CromwellTestKitSpec.scala
  server/src/test/scala/cromwell/engine/WorkflowManagerActorSpec.scala
Labels: Please re-review now

#4065 Autodetect & allow tabs in command blocks
  wdl/transforms/draft3/src/test/cases/cmd_strip_common_spaces.wdl
  wdl/transforms/draft3/src/test/cases/cmd_strip_common_tabs.wdl
  wdl/transforms/draft3/src/test/cases/cmd_whitespace_none.wdl
  wdl/transforms/draft3/src/test/cases/cmd_whitespace_spaces.wdl
  wdl/transforms/draft3/src/test/cases/cmd_whitespace_tabs.wdl
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/ast2wdlom/WdlFileToWdlomSpec.scala
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/wdlom2wom/WdlFileToWomSpec.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/AstToCommandSectionElement.scala
  womtool/src/test/resources/validate/wdl_draft3/invalid/cmd_whitespace_mixed_diff_lines/cmd_whitespace_mixed_diff_lines.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/cmd_whitespace_mixed_diff_lines/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/cmd_whitespace_mixed_same_line/cmd_whitespace_mixed_same_line.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/cmd_whitespace_mixed_same_line/error.txt
Labels: 🌲Redwood

#4075 Prevent anonymous expression nodes from teleporting values between scopes
  wdl/transforms/draft3/src/test/cases/same_named_inputs_priority.wdl
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/ast2wdlom/WdlFileToWdlomSpec.scala
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/wdlom2wom/WdlFileToWomSpec.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/WorkflowDefinitionElementToWomWorkflowDefinition.scala
Labels: 🌲Redwood

#4020 Initial ecs-agent proxy implementation
  .gitignore
  cloudSupport/src/main/scala/cromwell/cloudsupport/aws/s3/S3Storage.scala
  filesystems/s3/src/main/scala/cromwell/filesystems/s3/S3PathBuilder.scala
  project/Dependencies.scala
  project/build.properties
  scripts/perf/jenkins_script.sh
  scripts/perf/vm_scripts/docker-compose.yml
  supportedBackends/aws/src/main/resources/agent/build-agent
  supportedBackends/aws/src/main/resources/agent/launch_sidecar
  supportedBackends/aws/src/main/resources/agent/run-agent
  supportedBackends/aws/src/main/resources/agent/spawnoninput.go
  supportedBackends/aws/src/main/resources/ecs-proxy/Dockerfile
  supportedBackends/aws/src/main/resources/ecs-proxy/build-proxy
  supportedBackends/aws/src/main/resources/ecs-proxy/proxy
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchAsyncBackendJobExecutionActor.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchAttributes.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchConfiguration.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchJob.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchJobDefinition.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchParameters.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/package.scala
  supportedBackends/aws/src/test/scala/cromwell/backend/impl/aws/AwsBatchAttributesSpec.scala
  supportedBackends/aws/src/test/scala/cromwell/backend/impl/aws/AwsBatchConfigurationSpec.scala
  supportedBackends/aws/src/test/scala/cromwell/backend/impl/aws/AwsBatchJobSpec.scala
  supportedBackends/aws/src/test/scala/cromwell/backend/impl/aws/AwsBatchTestConfig.scala
Labels: AWS Backend

#4109 aws backend: support globbed outputs
  supportedBackends/aws/src/main/resources/ecs-proxy/proxy
Labels: AWS Backend

#4146 Dash-friendly `if`s.
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/api/ActionCommands.scala
  supportedBackends/google/pipelines/v2alpha1/src/test/scala/cromwell/backend/google/pipelines/v2alpha1/api/ActionCommandsSpec.scala
Labels: 🚧BLOCKS RELEASE🚧

#4135 There is no escape
  CHANGELOG.md
  centaur/src/main/resources/standardTestCases/wdl_biscayne/biscayne_as_map_et_al/biscayne_as_map_et_al.wdl
  centaur/src/main/resources/standardTestCases/wdl_biscayne/biscayne_http_relative_imports/biscayne_http_relative_imports.wdl
  centaur/src/main/resources/standardTestCases/wdl_biscayne/default_default/default_default.wdl
  centaur/src/main/resources/standardTestCases/wdl_draft3/draft3_http_imports/draft3_http_imports.wdl
  centaur/src/main/resources/standardTestCases/wdl_draft3/draft3_inline_python/draft3_inline_python.wdl
  centaur/src/main/resources/standardTestCases/wdl_draft3/draft3_size_of_optionals/draft3_size_of_optionals.wdl
  centaur/src/main/resources/standardTestCases/wdl_draft3/draft3_size_of_optionals/size_in_workflow_places.wdl
  centaur/src/main/resources/standardTestCases/workflow_url_biscayne_sub_wfs.test
  centaur/src/main/resources/standardTestCases/workflow_url_http_relative_imports.test
  languageFactories/wdl-biscayne/src/main/scala/languages/wdl/biscayne/WdlBiscayneLanguageFactory.scala
  languageFactories/wdl-draft3/src/main/scala/languages/wdl/draft3/WdlDraft3LanguageFactory.scala
  wdl/transforms/biscayne/src/main/java/wdl/biscayne/parser/WdlParser.java
  wdl/transforms/biscayne/src/test/cases/simple_first_test.wdl
  wdl/transforms/draft3/src/main/java/wdl/draft3/parser/WdlParser.java
  wdl/transforms/draft3/src/test/cases/string_escaping.wdl
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/ast2wdlom/WdlFileToWdlomSpec.scala
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/wdlom2wom/WdlFileToWomSpec.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wdl/WdlWriterImpl.scala
  womtool/src/main/scala/womtool/graph/WomGraph.scala
  womtool/src/test/resources/validate/biscayne/invalid/bad_task/bad_task.wdl
  womtool/src/test/resources/validate/biscayne/valid/http_relative_imports/http_relative_imports.wdl
  womtool/src/test/resources/validate/biscayne/valid/relative_imports/relative_imports.wdl
  womtool/src/test/resources/validate/biscayne/valid/relative_imports/structs/my_struct.wdl
  womtool/src/test/resources/validate/biscayne/valid/relative_imports/sub_wfs/foo.wdl
  womtool/src/test/resources/validate/biscayne/valid/relative_imports/sub_wfs/tasks/add5.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/HaplotypeCallerWF/HaplotypeCallerWF.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/arrays_v1/arrays_v1.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/cnv_somatic_pair_workflow/cnv_common_tasks.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/cnv_somatic_pair_workflow/cnv_somatic_oncotator_workflow.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/cnv_somatic_pair_workflow/cnv_somatic_pair_workflow.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/joint-discovery-gatk/joint-discovery-gatk.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/multiple_overridable_optionals/multiple_overridable_optionals.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/overridable_optionals/overridable_optionals.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/singlesample_v1/singlesample_v1.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/smartseq2_single_sample/HISAT2.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/smartseq2_single_sample/Picard.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/smartseq2_single_sample/RSEM.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/smartseq2_single_sample/smartseq2_single_sample.wdl
Labels: Comply with WDL Spec, 🌲Redwood

#4149 Fail on missing outputs 34 hotfix edition.
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/api/ActionCommands.scala
  supportedBackends/google/pipelines/v2alpha1/src/test/scala/cromwell/backend/google/pipelines/v2alpha1/api/ActionCommandsSpec.scala
Labels: HIGH PRIORITY, PAPI v2 Blocker, 🐛Bug

#3968 Allow declarations called 'version'
  wdl/transforms/biscayne/src/main/java/wdl/biscayne/parser/WdlParser.java
  wdl/transforms/biscayne/src/test/scala/wdl/transforms/biscayne/Ast2WdlomSpec.scala
  wdl/transforms/draft3/src/main/java/wdl/draft3/parser/WdlParser.java
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/ast2wdlom/Ast2WdlomSpec.scala
  womtool/src/test/resources/validate/biscayne/valid/version_variables/version_variables.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/version_variables/version_variables.wdl
Labels: Comply with WDL Spec, OpenWDL Blocked, 🌲Redwood
