Repository broadinstitute/cromwell, pull requests merged in 2018-04, with the labels that each got.

#3452 Call element WDLOM without inputs or outputs to WOM
  wdl/model/draft3/src/main/scala/wdl/model/draft3/graph/UnlinkedValueConsumer.scala
  wdl/model/draft3/src/main/scala/wdl/model/draft3/graph/UnlinkedValueGenerator.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/consumed/package.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/graph/LinkedGraphMaker.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/graph/package.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/FileElementToWomBundle.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/TaskDefinitionElementToWomTaskDefinition.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/WorkflowDefinitionElementToWomWorkflowDefinition.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/CallElementToGraphNode.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/IfElementToGraphNode.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/ScatterElementToGraphNode.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/WorkflowGraphElementToGraphNode.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/package.scala
  wdl/transforms/draft3/src/test/cases/no_input_no_output_workflow.wdl
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/wdlom2wom/WdlFileToWomSpec.scala
Labels: WDL Team PR

#3464 Only alter permissions when running on docker
  backend/src/main/scala/cromwell/backend/io/JobPaths.scala
  backend/src/main/scala/cromwell/backend/io/JobPathsWithDocker.scala
  backend/src/main/scala/cromwell/backend/standard/StandardExpressionFunctions.scala
  backend/src/main/scala/cromwell/backend/wdl/WriteFunctions.scala
  backend/src/test/scala/cromwell/backend/wdl/FileSizeSpec.scala
  core/src/main/scala/cromwell/core/core.scala
  engine/src/main/scala/cromwell/engine/io/nio/NioFlow.scala
  engine/src/main/scala/cromwell/engine/workflow/WorkflowManagerActor.scala
  supportedBackends/jes/src/test/scala/cromwell/backend/impl/jes/JesAsyncBackendJobExecutionActorSpec.scala
  supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystem.scala
  supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystemAsyncJobExecutionActor.scala
  supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystemInitializationActor.scala
  supportedBackends/spark/src/main/scala/cromwell/backend/impl/spark/SparkBackendFactory.scala
Labels: needs rebase ⚔

#3482 A couple of small fixes to help find call outputs
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/graph/package.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/WorkflowDefinitionElementToWomWorkflowDefinition.scala
  wdl/transforms/draft3/src/test/cases/simple_first_test.wdl
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/ast2wdlom/WdlFileToWdlomSpec.scala
Labels: WDL Team PR

#3481 Call with inputs to WOM
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/graph/package.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/WorkflowDefinitionElementToWomWorkflowDefinition.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/CallElementToGraphNode.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/WorkflowGraphElementToGraphNode.scala
  wdl/transforms/draft3/src/test/cases/simple_first_test.wdl
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/ast2wdlom/WdlFileToWdlomSpec.scala
Labels: WDL Team PR

#3470 CWL Restart
  backend/src/test/scala/cromwell/backend/wdl/OutputEvaluatorSpec.scala
  centaur/src/it/scala/centaur/CentaurTestSuite.scala
  centaur/src/main/resources/standardTestCases/cwl_restart/cwl_restart.cwl
  centaur/src/main/resources/standardTestCases/cwl_restart_local_with_recover.test
  core/src/main/resources/reference.conf
  core/src/main/scala/cromwell/core/simpleton/WomValueBuilder.scala
  core/src/main/scala/cromwell/core/simpleton/WomValueSimpleton.scala
  engine/src/main/scala/cromwell/Simpletons.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/job/EngineJobExecutionActor.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/materialization/MaterializeWorkflowDescriptorActor.scala
  engine/src/main/scala/cromwell/webservice/metadata/MetadataComponent.scala
  services/src/main/scala/cromwell/services/metadata/MetadataQuery.scala
  services/src/test/scala/cromwell/services/healthmonitor/HealthMonitorServiceActorSpec.scala
  src/bin/travis/resources/bcs_centaur.conf.ctmpl
  src/bin/travis/resources/jes_centaur.conf.ctmpl
  src/bin/travis/resources/tes_centaur.conf
Labels: Please re-review now

#3479 Add WDL draft 3 to womtool validation tests
  womtool/src/test/resources/validate/wdl_draft2/invalid/extra_input/error.txt
  womtool/src/test/resources/validate/wdl_draft2/invalid/extra_input/extra_input.inputs.json
  womtool/src/test/resources/validate/wdl_draft2/invalid/extra_input/extra_input.wdl
  womtool/src/test/resources/validate/wdl_draft2/invalid/just_braces/error.txt
  womtool/src/test/resources/validate/wdl_draft2/invalid/just_braces/just_braces.wdl
  womtool/src/test/resources/validate/wdl_draft2/invalid/missing_input/error.txt
  womtool/src/test/resources/validate/wdl_draft2/invalid/missing_input/missing_input.inputs.json
  womtool/src/test/resources/validate/wdl_draft2/invalid/missing_input/missing_input.wdl
  womtool/src/test/resources/validate/wdl_draft2/invalid/unwanted_value_provided/error.txt
  womtool/src/test/resources/validate/wdl_draft2/invalid/unwanted_value_provided/unwanted_value_provided.wdl
  womtool/src/test/resources/validate/wdl_draft2/valid/needs_an_input/needs_an_input.wdl
  womtool/src/test/resources/validate/wdl_draft2/valid/three_step/three_step.wdl
  womtool/src/test/resources/validate/wdl_draft3/ignored/three_step/three_step.wdl
  womtool/src/test/resources/validate/wdl_draft3/ignored/unwanted_task_input/error.txt
  womtool/src/test/resources/validate/wdl_draft3/ignored/unwanted_task_input/unwanted_task_input.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/extra_input/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/extra_input/extra_input.inputs.json
  womtool/src/test/resources/validate/wdl_draft3/invalid/extra_input/extra_input.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/input_for_declaration/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/input_for_declaration/input_for_declaration.inputs.json
  womtool/src/test/resources/validate/wdl_draft3/invalid/input_for_declaration/input_for_declaration.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/just_braces/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/just_braces/just_braces.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/missing_input/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/missing_input/missing_input.inputs.json
  womtool/src/test/resources/validate/wdl_draft3/invalid/missing_input/missing_input.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/nested_imports_with_bad_input/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/nested_imports_with_bad_input/import_layer_1.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/nested_imports_with_bad_input/import_layer_2.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/nested_imports_with_bad_input/nested_imports_with_bad_input.inputs.json
  womtool/src/test/resources/validate/wdl_draft3/invalid/nested_imports_with_bad_input/nested_imports_with_bad_input.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/needs_an_input/needs_an_input.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/nested_imports_with_input/import_layer_1.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/nested_imports_with_input/import_layer_2.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/nested_imports_with_input/nested_imports_with_input.inputs.json
  womtool/src/test/resources/validate/wdl_draft3/valid/nested_imports_with_input/nested_imports_with_input.wdl
  womtool/src/test/scala/womtool/WomtoolValidateDraft2Spec.scala
  womtool/src/test/scala/womtool/WomtoolValidateSpec.scala
Labels: Red Thumb Required

#3491 Draft 3 forkjoin
  centaur/src/main/resources/standardTestCases/draft3_forkjoin.test
  centaur/src/main/resources/standardTestCases/wdl_draft3/forkjoin/forkjoin.inputs
  centaur/src/main/resources/standardTestCases/wdl_draft3/forkjoin/forkjoin.wdl
  common/src/main/scala/common/validation/ErrorOr.scala
  wdl/model/draft2/src/main/scala/wdl/draft2/model/expression/FileEvaluator.scala
  wdl/model/draft3/src/main/scala/wdl/model/draft3/graph/expression/FileEvaluator.scala
  wdl/model/shared/src/main/scala/wdl/shared/model/expression/FileEvaluatorUtil.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/files/BinaryOperatorEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/files/EngineFunctionEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/files/LiteralEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/files/LookupEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/files/TernaryIfEvaluator.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/files/UnaryOperatorEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/files/package.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/values/EngineFunctionEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/values/package.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/CommandPartElementToWomCommandPart.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/WorkflowDefinitionElementToWomWorkflowDefinition.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/expression/WdlomWomExpression.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/graph/CallElementToGraphNode.scala
  wom/src/main/scala/wom/graph/WomIdentifier.scala
Labels: WDL Team PR

#3525 Centaur BCS
  .travis.yml
  backend/src/main/scala/cromwell/backend/standard/StandardAsyncExecutionActor.scala
  backend/src/main/scala/cromwell/backend/validation/RuntimeAttributesValidation.scala
  centaur/test_cromwell.sh
  docs/backends/BCS.md
  docs/tutorials/BCSIntro.md
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/SqlWorkflowStore.scala
  filesystems/oss/src/main/scala/cromwell/filesystems/oss/nio/OssAppendOutputStream.scala
  filesystems/oss/src/main/scala/cromwell/filesystems/oss/nio/OssFileReadChannel.scala
  filesystems/oss/src/main/scala/cromwell/filesystems/oss/nio/OssStorageFileAttributesView.scala
  filesystems/oss/src/main/scala/cromwell/filesystems/oss/nio/OssStorageFileSystem.scala
  filesystems/oss/src/main/scala/cromwell/filesystems/oss/nio/OssStorageFileSystemProvider.scala
  filesystems/oss/src/test/scala/cromwell/filesystems/oss/nio/OssNioUtilSpec.scala
  filesystems/oss/src/test/scala/cromwell/filesystems/oss/nio/OssStorageFileAttributesViewSpec.scala
  project/Dependencies.scala
  src/bin/travis/resources/bcs_centaur.conf.ctmpl
  src/bin/travis/testCentaurBcs.sh
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/BcsAsyncBackendJobExecutionActor.scala
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/BcsExpressionFunctions.scala
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/BcsJob.scala
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/BcsRuntimeAttributes.scala
Labels: Alibaba Cloud

#3535 Array indexing
  centaur/src/main/resources/standardTestCases/draft3_array_indexing.test
  centaur/src/main/resources/standardTestCases/wdl_draft3/array_indexing/array_indexing.wdl
  wdl/model/draft3/src/main/scala/wdl/model/draft3/elements/ExpressionElement.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/ast2wdlom/AstNodeToExpressionElement.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/consumed/LookupEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/consumed/package.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/files/LookupEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/files/package.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/types/LookupEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/types/package.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/values/LookupEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/values/package.scala
Labels: Redwood Thumb Required

#3547 Test struct localization and delocalization
  centaur/src/main/resources/standardTestCases/draft3_struct_localize_delocalize.test
  centaur/src/main/resources/standardTestCases/wdl_draft3/struct_localize_delocalize/struct_localize_delocalize.wdl
  wdl/model/shared/src/main/scala/wdl/shared/model/expression/FileEvaluatorUtil.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/files/LiteralEvaluators.scala
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/linking/expression/files/FileEvaluatorSpec.scala
Labels: Redwood Thumb Required

#3545 Wire in draft3 globs
  centaur/src/main/resources/standardTestCases/draft3_globs.test
  centaur/src/main/resources/standardTestCases/wdl_draft3/globs/globs.wdl
  wdl/model/draft3/src/main/scala/wdl/model/draft3/elements/ExpressionElement.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/ast2wdlom/AstNodeToExpressionElement.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/consumed/EngineFunctionEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/consumed/package.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/files/EngineFunctionEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/files/package.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/types/EngineFunctionEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/types/package.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/values/EngineFunctionEvaluators.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/linking/expression/values/package.scala
  wdl/transforms/draft3/src/main/scala/wdl/draft3/transforms/wdlom2wom/CommandPartElementToWomCommandPart.scala
Labels: Redwood Thumb Required
