Repository broadinstitute/cromwell, pull requests merged in 2019-07, with the labels that each got.

#5034 Make the file read limits effectively "opt-in" [BA-5723]
  core/src/main/resources/reference.conf
  src/ci/resources/build_application.inc.conf
Labels: Very Low Priority

#5053 Meta section [BA-5797]
  cwl/src/main/scala/cwl/Workflow.scala
  services/src/main/scala/cromwell/services/womtool/models/MetaValueElementJsonSupport.scala
  services/src/main/scala/cromwell/services/womtool/models/WorkflowDescription.scala
  wdl/transforms/draft2/src/main/scala/wdl/transforms/draft2/wdlom2wom/WdlDraft2WomCommandTaskDefinitionMaker.scala
  wdl/transforms/draft2/src/main/scala/wdl/transforms/draft2/wdlom2wom/WdlDraft2WomWorkflowDefinitionMaker.scala
  wdl/transforms/draft3/src/test/cases/task_with_metas2.wdl
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/ast2wdlom/WdlFileToWdlomSpec.scala
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/wdlom2wom/WdlFileToWomSpec.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/Util.scala
  wom/src/main/scala/wom/callable/CommandTaskDefinition.scala
  wom/src/main/scala/wom/callable/WorkflowDefinition.scala
  wom/src/test/resources/three_step/test.wdl
  womtool/src/main/scala/womtool/wom2wdlom/WomToWdlom.scala
Labels: Community Contribution

#5061 Nested scatters [BA-5803]
  languageFactories/cwl-v1-0/src/main/scala/languages/cwl/CwlV1_0LanguageFactory.scala
  languageFactories/language-factory-core/src/main/scala/cromwell/languages/LanguageFactory.scala
  languageFactories/wdl-biscayne/src/main/scala/languages/wdl/biscayne/WdlBiscayneLanguageFactory.scala
  languageFactories/wdl-draft2/src/main/scala/languages/wdl/draft2/WdlDraft2LanguageFactory.scala
  languageFactories/wdl-draft3/src/main/scala/languages/wdl/draft3/WdlDraft3LanguageFactory.scala
  wdl/transforms/draft3/src/test/cases/two_level_scatter.wdl
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/ast2wdlom/WdlFileToWdlomSpec.scala
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/wdlom2wom/WdlFileToWomSpec.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/FileElementToWomBundle.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/WorkflowDefinitionElementToWomWorkflowDefinition.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/graph/IfElementToGraphNode.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/graph/ScatterElementToGraphNode.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/graph/WorkflowGraphElementToGraphNode.scala
  wom/src/main/resources/reference.conf
  womtool/src/main/scala/womtool/graph/WomGraph.scala
Labels: Community Contribution

#4992 AlibabaCloud add docker registry, callcaching, glob supports [BA-5647]
  CHANGELOG.md
  core/src/main/resources/reference.conf
  cromwell.example.backends/BCS.conf
  dockerHashing/src/main/scala/cromwell/docker/DockerInfoActor.scala
  dockerHashing/src/main/scala/cromwell/docker/registryv2/flows/alibabacloudcr/AlibabaCloudCRRegistry.scala
  dockerHashing/src/test/scala/cromwell/docker/DockerImageIdentifierSpec.scala
  dockerHashing/src/test/scala/cromwell/docker/registryv2/AlibabaCloudCRRegistrySpec.scala
  docs/backends/BCS.md
  docs/cromwell_features/CallCaching.md
  docs/tutorials/BCSIntro.md
  engine/src/main/scala/cromwell/engine/io/nio/NioFlow.scala
  filesystems/oss/src/main/scala/cromwell/filesystems/oss/OssPathBuilder.scala
  filesystems/oss/src/main/scala/cromwell/filesystems/oss/OssPathBuilderFactory.scala
  filesystems/oss/src/main/scala/cromwell/filesystems/oss/batch/OssBatchCommandBuilder.scala
  filesystems/oss/src/main/scala/cromwell/filesystems/oss/batch/OssBatchIoCommand.scala
  filesystems/oss/src/main/scala/cromwell/filesystems/oss/nio/OssFileReadChannel.scala
  filesystems/oss/src/main/scala/cromwell/filesystems/oss/nio/OssStorageFileAttributesView.scala
  filesystems/oss/src/main/scala/cromwell/filesystems/oss/nio/OssStorageFileSystem.scala
  filesystems/oss/src/main/scala/cromwell/filesystems/oss/nio/OssStorageFileSystemProvider.scala
  filesystems/oss/src/main/scala/cromwell/filesystems/oss/nio/TTLOssStorageConfiguration.scala
  filesystems/oss/src/test/scala/cromwell/filesystems/oss/OssPathBuilderSpec.scala
  filesystems/oss/src/test/scala/cromwell/filesystems/oss/nio/OssNioUtilSpec.scala
  filesystems/oss/src/test/scala/cromwell/filesystems/oss/nio/TTLOssStorageConfigurationSpec.scala
  project/Dependencies.scala
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/BcsAsyncBackendJobExecutionActor.scala
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/BcsBackendLifecycleActorFactory.scala
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/BcsClusterIdOrConfiguration.scala
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/BcsConfiguration.scala
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/BcsJob.scala
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/BcsJobCachingActorHelper.scala
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/BcsJobPaths.scala
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/BcsMount.scala
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/BcsRuntimeAttributes.scala
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/BcsWorkflowPaths.scala
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/callcaching/BcsBackendCacheHitCopyingActor.scala
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/callcaching/BcsCacheHitDuplicationStrategy.scala
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/worker.tar.gz
  supportedBackends/bcs/src/test/resources/application.conf
  supportedBackends/bcs/src/test/scala/cromwell/backend/impl/bcs/BcsClusterIdOrConfigurationSpec.scala
  supportedBackends/bcs/src/test/scala/cromwell/backend/impl/bcs/BcsConfigurationSpec.scala
  supportedBackends/bcs/src/test/scala/cromwell/backend/impl/bcs/BcsJobPathsSpec.scala
  supportedBackends/bcs/src/test/scala/cromwell/backend/impl/bcs/BcsJobSpec.scala
  supportedBackends/bcs/src/test/scala/cromwell/backend/impl/bcs/BcsMountSpec.scala
  supportedBackends/bcs/src/test/scala/cromwell/backend/impl/bcs/BcsRuntimeAttributesSpec.scala
  supportedBackends/bcs/src/test/scala/cromwell/backend/impl/bcs/BcsTestUtilSpec.scala
  supportedBackends/bcs/src/test/scala/cromwell/backend/impl/bcs/BcsWorkflowPathsSpec.scala
  supportedBackends/bcs/src/test/scala/cromwell/backend/impl/bcs/callcaching/BcsBackendCacheHitCopyingActorSpec.scala
Labels: Back With Originator ♻️, Community Contribution, Sprint 3

#5082 Create TORQUE.conf [BA-5845]
  cromwell.example.backends/TORQUE.conf
Labels: Community Contribution
