Repository broadinstitute/cromwell, pull requests merged in 2019-08, with the labels that each got.

#5111 Alibaba Cloud backend supports CR in VPC. [BA-5928]
  dockerHashing/src/main/scala/cromwell/docker/registryv2/flows/alibabacloudcr/AlibabaCloudCRRegistry.scala
  dockerHashing/src/test/scala/cromwell/docker/registryv2/AlibabaCloudCRRegistrySpec.scala
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/BcsBackendLifecycleActorFactory.scala
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/BcsConfiguration.scala
Labels: Community Contribution

#5104 fix for the problem with running single tasks described by CWL [BA-4969]
  server/src/main/scala/cromwell/CromwellEntryPoint.scala
  server/src/test/scala/cromwell/CromwellCommandLineSpec.scala
Labels: CWL, Community Contribution

#5141 Parallelize GCS file input localization [BA-5899]
  centaur/src/main/resources/papiUpgradeTestCases/papi_upgrade/papi_upgrade.wdl
  centaur/src/main/resources/standardTestCases/lots_of_inputs.test
  centaur/src/main/resources/standardTestCases/lots_of_inputs/lots_of_inputs.inputs
  centaur/src/main/resources/standardTestCases/lots_of_inputs/lots_of_inputs.wdl
  centaur/src/main/resources/standardTestCases/lots_of_inputs/lots_of_inputs_papiv2.inputs
  centaur/src/main/resources/standardTestCases/lots_of_inputs_papiv2.test
  supportedBackends/google/pipelines/v2alpha1/src/main/resources/gcs_transfer.sh
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/PipelinesApiAsyncBackendJobExecutionActor.scala
Labels: Please re-review now
