Repository broadinstitute/cromwell, pull requests merged in 2019-05, with the labels that each got.

#4878 add relative output paths change to changelog.
  CHANGELOG.md
  docs/wf_options/Overview.md
Labels: External Contributor

#4893 Make invalidate_bad_caches_jes_no_copy more deterministic
  centaur/src/main/resources/standardTestCases/invalidate_bad_caches/invalidate_bad_caches_no_copy.wdl
  centaur/src/main/resources/standardTestCases/invalidate_bad_caches_jes_no_copy.test
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/job/EngineJobExecutionActor.scala
Labels: Back With Originator ♻️

#4905 Clarify exit-code-timeout-seconds docs
  cromwell.example.backends/HtCondor.conf
  cromwell.example.backends/SGE.conf
  cromwell.example.backends/slurm.conf
  docs/backends/HPC.md
Labels: External Contributor

#4924 [develop] Job execution token dispenser actor fixes
  engine/src/main/scala/cromwell/engine/workflow/tokens/JobExecutionTokenDispenserActor.scala
  engine/src/main/scala/cromwell/engine/workflow/tokens/TokenQueue.scala
  engine/src/main/scala/cromwell/engine/workflow/tokens/UnhoggableTokenPool.scala
  engine/src/test/scala/cromwell/engine/workflow/tokens/JobExecutionTokenDispenserActorSpec.scala
Labels: 🚧BLOCKS RELEASE🚧

#4947 Safety net against long running "log an event" actions
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/api/ActionBuilder.scala
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/api/ActionCommands.scala
  supportedBackends/google/pipelines/v2alpha1/src/test/scala/cromwell/backend/google/pipelines/v2alpha1/PipelinesConversionsSpec.scala
Labels: User Requested Improvement, 🤕Hotfix Candidate

#4952 Defend against over-large stderr files
  core/src/main/scala/cromwell/core/path/EvenBetterPathMethods.scala
  engine/src/main/scala/cromwell/engine/io/nio/NioFlow.scala
  engine/src/main/scala/cromwell/engine/workflow/WorkflowManagerActor.scala
Labels: 🤕Hotfix Candidate

#4958 Stop excluding AWS glob tests
  src/ci/bin/testCentaurAws.sh
Labels: 🚧BLOCKS RELEASE🚧

#4957 Remove travis workaround
  src/ci/bin/testDockerScripts.sh
Labels: 🚧BLOCKS RELEASE🚧

#4939 Custom GPUs
  CHANGELOG.md
  backend/src/main/scala/cromwell/backend/validation/ValidatedRuntimeAttributesBuilder.scala
  centaur/src/main/resources/standardTestCases/gpu_cuda_image.test
  centaur/src/main/resources/standardTestCases/gpu_on_papi.test
  centaur/src/main/resources/standardTestCases/gpu_on_papi/gpu_cuda_image.wdl
  centaur/src/main/resources/standardTestCases/gpu_on_papi/gpu_on_papi.wdl
  centaur/src/main/resources/standardTestCases/gpu_on_papi/invalid.inputs.json
  centaur/src/main/resources/standardTestCases/gpu_on_papi/valid.inputs.json
  centaur/src/main/resources/standardTestCases/gpu_on_papi_invalid.test
  centaur/src/main/resources/standardTestCases/gpu_on_papi_valid.test
  src/ci/bin/testCentaurPapiV1.sh
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/GpuTypeValidation.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/GpuValidation.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/PapiInstrumentation.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/PipelinesApiRuntimeAttributes.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/api/PipelinesApiRequestManager.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/api/PipelinesApiRequestWorker.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/api/clients/PipelinesApiRunCreationClient.scala
  supportedBackends/google/pipelines/common/src/test/scala/cromwell/backend/google/pipelines/common/PipelinesApiGpuAttributesSpec.scala
  supportedBackends/google/pipelines/common/src/test/scala/cromwell/backend/google/pipelines/common/PipelinesApiRuntimeAttributesSpec.scala
  supportedBackends/google/pipelines/v1alpha2/src/main/scala/cromwell/backend/google/pipelines/v1alpha2/api/request/AbortRequestHandler.scala
  supportedBackends/google/pipelines/v1alpha2/src/main/scala/cromwell/backend/google/pipelines/v1alpha2/api/request/GetRequestHandler.scala
  supportedBackends/google/pipelines/v1alpha2/src/main/scala/cromwell/backend/google/pipelines/v1alpha2/api/request/RunRequestHandler.scala
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/GenomicsFactory.scala
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/api/request/AbortRequestHandler.scala
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/api/request/GetRequestHandler.scala
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/api/request/RunRequestHandler.scala
Labels: 🚧BLOCKS RELEASE🚧

#4959 Always shift times to UTC, and render w/ 3 digits of millis
  CHANGELOG.md
  centaur/src/it/scala/centaur/reporting/BigQueryReporter.scala
  common/src/main/scala/common/util/TimeUtil.scala
  cromwellApiClient/src/main/scala/cromwell/api/model/TimeUtil.scala
  cromwellApiClient/src/main/scala/cromwell/api/model/package.scala
  cromwellApiClient/src/test/scala/cromwell/api/model/CromwellQueryResultJsonFormatterSpec.scala
  engine/src/main/scala/cromwell/engine/workflow/WorkflowMetadataHelper.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/SqlWorkflowStore.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/WorkflowStoreSubmitActor.scala
  engine/src/main/scala/cromwell/webservice/WorkflowJsonSupport.scala
  services/src/main/scala/cromwell/services/metadata/MetadataJsonSupport.scala
  services/src/main/scala/cromwell/services/metadata/MetadataQuery.scala
  services/src/test/scala/cromwell/services/metadata/impl/MetadataDatabaseAccessSpec.scala
Labels: 🚧BLOCKS RELEASE🚧

#4951 Call cache no copy fixups and centaur error improvements
  centaur/src/it/scala/centaur/reporting/Slf4jReporter.scala
  centaur/src/main/resources/standardTestCases/invalidate_bad_caches_jes_no_copy.test
  centaur/src/main/scala/centaur/test/Test.scala
Labels: ⭐ Two Thumbs-Up ⭐

#4859 [develop] Cleanup AWS Documentation in Hackathon
  docs/RuntimeAttributes.md
  docs/backends/AWSBatch.md
  docs/tutorials/AwsBatch101.md
  mkdocs.yml
Labels: AWS Backend

#4961 Have the right horicromtitude
  centaur/src/it/scala/centaur/AbstractCentaurTestCaseSpec.scala
  centaur/src/it/scala/centaur/CentaurTestSuite.scala
  centaur/src/it/scala/centaur/ExternalTestCaseSpec.scala
  centaur/src/it/scala/centaur/ParallelTestCaseSpec.scala
  centaur/src/it/scala/centaur/SequentialTestCaseSpec.scala
  centaur/src/it/scala/centaur/StandardTestCaseSpec.scala
  centaur/src/main/scala/centaur/CromwellTracker.scala
  centaur/src/main/scala/centaur/test/formulas/TestFormulas.scala
  centaur/src/main/scala/centaur/test/standard/CentaurTestCase.scala
  centaur/src/main/scala/centaur/test/standard/CentaurTestFormat.scala
  centaurCwlRunner/src/main/scala/centaur/cwl/CentaurCwlRunner.scala
  core/src/main/scala/cromwell/core/WorkflowProcessingEvents.scala
  database/sql/src/main/scala/cromwell/database/slick/WorkflowStoreSlickDatabase.scala
  database/sql/src/main/scala/cromwell/database/slick/tables/WorkflowStoreEntryComponent.scala
  database/sql/src/main/scala/cromwell/database/sql/WorkflowStoreSqlDatabase.scala
  engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala
  engine/src/main/scala/cromwell/engine/workflow/WorkflowProcessingEventPublishing.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/InMemoryWorkflowStore.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/SqlWorkflowStore.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/WorkflowStore.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/WorkflowStoreEngineActor.scala
  engine/src/main/scala/cromwell/server/CromwellShutdown.scala
  project/Dependencies.scala
  scripts/docker-compose-mysql/docker-compose-horicromtal.yml
  src/ci/bin/test.inc.sh
  src/ci/bin/testCentaurHoricromtalPapiV2.sh
  src/ci/resources/centaur_application_horicromtal.conf
  src/ci/resources/centaur_application_horicromtal_no_assert.conf
  src/ci/resources/papi_v2_horicromtal_application.conf
Labels: ⬅️ horicromtal ➡️

#4968 [Release Script] Make checkout mode an option
  release/release_inputs.json
  release/release_options.json
  release/release_workflow.wdl
Labels: Sprint 2 Planned

#4940 Womtool endpoint: indicate when a workflow itself is valid, not considering inputs
  CHANGELOG.md
  CromIAM/src/main/resources/swagger/cromiam.yaml
  docs/api/RESTAPI.md
  engine/src/main/resources/swagger/cromwell.yaml
  engine/src/test/scala/cromwell/webservice/routes/CromwellApiServiceSpec.scala
  engine/src/test/scala/cromwell/webservice/routes/WomtoolRouteSupportSpec.scala
  services/src/main/scala/cromwell/services/womtool/Describer.scala
  services/src/main/scala/cromwell/services/womtool/models/WorkflowDescription.scala
  services/src/test/resources/describe/wdl_1_0/arrays/description.json
  services/src/test/resources/describe/wdl_1_0/basics/description.json
  services/src/test/resources/describe/wdl_1_0/cant_parse_draft_2/description.json
  services/src/test/resources/describe/wdl_1_0/empty_workflow/description.json
  services/src/test/resources/describe/wdl_1_0/invalid_workflow/description.json
  services/src/test/resources/describe/wdl_1_0/name_from_task/description.json
  services/src/test/resources/describe/wdl_1_0/name_from_workflow/description.json
  services/src/test/resources/describe/wdl_1_0/name_none_from_tasks/description.json
  services/src/test/resources/describe/wdl_1_0/nested_map/description.json
  services/src/test/resources/describe/wdl_1_0/objects/description.json
  services/src/test/resources/describe/wdl_1_0/whitespace_workflow/description.json
  services/src/test/resources/describe/wdl_draft_2/arrays/description.json
  services/src/test/resources/describe/wdl_draft_2/basics/description.json
  services/src/test/resources/describe/wdl_draft_2/cant_parse_1_0/description.json
  services/src/test/resources/describe/wdl_draft_2/empty_workflow/description.json
  services/src/test/resources/describe/wdl_draft_2/invalid_workflow/description.json
  services/src/test/resources/describe/wdl_draft_2/name_from_task/description.json
  services/src/test/resources/describe/wdl_draft_2/name_from_workflow/description.json
  services/src/test/resources/describe/wdl_draft_2/name_none_from_tasks/description.json
  services/src/test/resources/describe/wdl_draft_2/nested_map/description.json
  services/src/test/resources/describe/wdl_draft_2/objects/description.json
  services/src/test/resources/describe/wdl_draft_2/whitespace_workflow/description.json
  services/src/test/scala/cromwell/services/womtool/impl/WomtoolServiceInCromwellActorSpec.scala
Labels: Back With Originator ♻️

#4907 Virtual Private Network
  CHANGELOG.md
  centaur/src/main/resources/standardTestCases/check_network_in_vpc.test
  centaur/src/main/resources/standardTestCases/virtual_private_cloud/check_network_in_vpc.wdl
  centaur/src/main/resources/standardTestCases/workbench_health_monitor_check_papiv2.test
  cromwell.example.backends/PAPIv2.conf
  docs/backends/Google.md
  project/Dependencies.scala
  src/ci/resources/papi_v2_application.conf
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/PipelinesApiAsyncBackendJobExecutionActor.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/PipelinesApiAttributes.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/api/PipelinesApiRequestFactory.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/callcaching/PipelinesApiBackendCacheHitCopyingActor.scala
  supportedBackends/google/pipelines/common/src/test/scala/cromwell/backend/google/pipelines/common/PipelinesApiAttributesSpec.scala
  supportedBackends/google/pipelines/v1alpha2/src/test/scala/cromwell/backend/google/pipelines/v1alpha2/api/StatusResponseParsingSpec.scala
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/GenomicsFactory.scala
Labels: Back With Originator ♻️

#4938 Adding line numbers to workflow definitions
  core/src/test/scala/cromwell/util/WomMocks.scala
  cwl/src/main/scala/cwl/Workflow.scala
  wdl/model/draft3/src/main/scala/wdl/model/draft3/elements/LanguageElement.scala
  wdl/model/draft3/src/main/scala/wdl/model/draft3/elements/WorkflowDefinitionElement.scala
  wdl/transforms/biscayne/src/test/scala/wdl/transforms/biscayne/ast2wdlom/WdlFileToWdlomSpec.scala
  wdl/transforms/draft2/src/main/scala/wdl/transforms/draft2/wdlom2wom/WdlDraft2WomWorkflowDefinitionMaker.scala
  wdl/transforms/draft3/src/test/cases/cmd_whitespace_spaces.wdl
  wdl/transforms/draft3/src/test/cases/simple_conditional.wdl
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/ast2wdlom/WdlFileToWdlomSpec.scala
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/wdlom2wdl/WdlomToWdlFileSpec.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/AstToWorkflowDefinitionElement.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/GenericAst.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/WorkflowDefinitionElementToWomWorkflowDefinition.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/graph/ScatterElementToGraphNode.scala
  wom/src/main/scala/wom/callable/WorkflowDefinition.scala
  wom/src/main/scala/wom/graph/Graph.scala
  wom/src/main/scala/wom/package.scala
  wom/src/test/scala/wom/graph/GraphSpec.scala
  womtool/src/main/scala/womtool/wom2wdlom/WomToWdlom.scala
Labels: External Contributor, Sprint 2 Planned

#4995 Update issue template to point to Jira
  .github/issue_template.md
Labels: Sprint 2 Planned

#4988 Batch backend supports GCR public images
  docs/cromwell_features/CallCaching.md
Labels: Bonus, Sprint 2 Planned

#4996 Do-It-Ourselves Perf Testing
  processes/release_processes/README.MD
  processes/release_processes/firecloud-develop.dot
  processes/release_processes/firecloud-develop.dot.png
  processes/release_processes/perf-test.dot
  processes/release_processes/perf-test.dot.png
Labels: Bonus, Sprint 2 Planned

#4871 [develop] Status polling and submit limiting to ease AWS 429s
  CHANGELOG.md
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchAsyncBackendJobExecutionActor.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchBackendLifecycleActorFactory.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchSingletonActor.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/IntervalLimitedAwsJobSubmitActor.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/OccasionalStatusPollingActor.scala
Labels: AWS Backend, Back With Originator ♻️, Sprint 2 Planned

#5007 Enquicken the aws centaur now that 4871 is merged
  src/ci/resources/aws_application.conf
Labels: Back With Originator ♻️

#4977 Line numbers for calls and tasks
  core/src/test/scala/cromwell/util/WomMocks.scala
  cwl/src/main/scala/cwl/CommandLineTool.scala
  cwl/src/main/scala/cwl/WorkflowStep.scala
  engine/src/test/scala/cromwell/engine/workflow/lifecycle/execution/job/preparation/CallPreparationSpec.scala
  engine/src/test/scala/cromwell/engine/workflow/lifecycle/execution/job/preparation/JobPreparationTestHelper.scala
  wdl/model/draft3/src/main/scala/wdl/model/draft3/elements/CallElement.scala
  wdl/model/draft3/src/main/scala/wdl/model/draft3/elements/LanguageElement.scala
  wdl/model/draft3/src/main/scala/wdl/model/draft3/elements/ScatterElement.scala
  wdl/model/draft3/src/main/scala/wdl/model/draft3/elements/TaskDefinitionElement.scala
  wdl/model/draft3/src/main/scala/wdl/model/draft3/elements/WorkflowDefinitionElement.scala
  wdl/transforms/biscayne/src/test/cases/no_input_no_output_workflow.wdl
  wdl/transforms/biscayne/src/test/scala/wdl/transforms/biscayne/ast2wdlom/WdlFileToWdlomSpec.scala
  wdl/transforms/draft2/src/main/scala/wdl/transforms/draft2/wdlom2wom/WdlDraft2WomCallNodeMaker.scala
  wdl/transforms/draft2/src/main/scala/wdl/transforms/draft2/wdlom2wom/WdlDraft2WomCommandTaskDefinitionMaker.scala
  wdl/transforms/draft3/src/test/cases/no_input_no_output_workflow.wdl
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/ast2wdlom/WdlFileToWdlomSpec.scala
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/wdlom2wdl/WdlomToWdlFileSpec.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/AstToCallElement.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/AstToScatterElement.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/AstToTaskDefinitionElement.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/AstToWorkflowDefinitionElement.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/linking/graph/LinkedGraphMaker.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/TaskDefinitionElementToWomTaskDefinition.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/WorkflowDefinitionElementToWomWorkflowDefinition.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/graph/CallElementToGraphNode.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/graph/ScatterElementToGraphNode.scala
  wom/src/main/scala/wom/callable/Callable.scala
  wom/src/main/scala/wom/callable/CommandTaskDefinition.scala
  wom/src/main/scala/wom/callable/WorkflowDefinition.scala
  wom/src/main/scala/wom/graph/CallNode.scala
  wom/src/test/scala/wom/callable/CommandTaskDefinitionSpec.scala
  wom/src/test/scala/wom/graph/ExpressionAsCallInputSpec.scala
  wom/src/test/scala/wom/graph/GraphSpec.scala
  wom/src/test/scala/wom/graph/ScatterNodeSpec.scala
  womtool/src/main/scala/womtool/wom2wdlom/WomToWdlom.scala
  womtool/src/test/resources/validate/biscayne/invalid/after_circle/error.txt
Labels: <=== READY FOR REVIEW !!!, External Contributor, Sprint 2 Planned
