Repository broadinstitute/cromwell, pull requests merged in 2019-01, with the labels that each got.

#4503 CTKS Postfix Tests Centaurized
  centaur/src/main/resources/standardTestCases/postfix.test
  centaur/src/main/resources/standardTestCases/postfix_quantifiers/postfix_quantifiers.wdl
  server/src/test/scala/cromwell/PostfixQuantifierWorkflowSpec.scala
Labels: <=== READY FOR REVIEW !!!

#4516 Centaurify (de-CTKS) scatter test.
  centaur/src/main/resources/standardTestCases/scatter_simples/bag_of_tasks.wdl
  centaur/src/main/resources/standardTestCases/scatter_simples/prepare_scatter_gather.inputs
  centaur/src/main/resources/standardTestCases/scatter_simples/prepare_scatter_gather.wdl
  centaur/src/main/resources/standardTestCases/scatter_simples/scatter.wdl
  centaur/src/main/resources/standardTestCases/scatter_simples/siblings_scatter.wdl
  centaur/src/main/resources/standardTestCases/scatter_simples/simple_scatter.wdl
  centaur/src/main/resources/standardTestCases/scatter_simples_prepare_scatter_gather_local.test
  centaur/src/main/resources/standardTestCases/scatter_simples_prepare_scatter_gather_papi.test
  centaur/src/main/resources/standardTestCases/scatter_simples_scatter.test
  centaur/src/main/resources/standardTestCases/scatter_simples_siblings_scatter.test
  centaur/src/main/resources/standardTestCases/scatter_simples_simple_scatter.test
  core/src/test/scala/cromwell/util/SampleWdl.scala
  server/src/test/scala/cromwell/ScatterWorkflowSpec.scala
Labels: QA Triage

#4525 Increase connection pool timeout for unit tests
  core/src/test/resources/application.conf
Labels: QA Triage

#4483 [WDL Biscayne] 'after' keyword
  centaur/src/main/resources/standardTestCases/afters.test
  centaur/src/main/resources/standardTestCases/afters/afters.options.json
  centaur/src/main/resources/standardTestCases/afters/afters.wdl
  centaur/src/main/resources/standardTestCases/afters/afters_and_ifs.wdl
  centaur/src/main/resources/standardTestCases/afters/afters_and_scatters.wdl
  centaur/src/main/resources/standardTestCases/afters_and_ifs.test
  centaur/src/main/resources/standardTestCases/afters_and_scatters.test
  core/src/main/scala/cromwell/core/JobKey.scala
  core/src/test/scala/cromwell/util/WomMocks.scala
  cwl/src/main/scala/cwl/WorkflowStep.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/WorkflowExecutionActor.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/keys/ScatterKey.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/keys/ScatteredCallCompletionKey.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/stores/ExecutionStore.scala
  engine/src/test/scala/cromwell/engine/workflow/lifecycle/execution/job/preparation/CallPreparationSpec.scala
  engine/src/test/scala/cromwell/engine/workflow/lifecycle/execution/job/preparation/JobPreparationTestHelper.scala
  wdl/model/draft3/src/main/scala/wdl/model/draft3/elements/CallElement.scala
  wdl/model/draft3/src/main/scala/wdl/model/draft3/graph/GeneratedValueHandle.scala
  wdl/model/draft3/src/main/scala/wdl/model/draft3/graph/UnlinkedConsumedValueHook.scala
  wdl/transforms/biscayne/src/main/java/wdl/biscayne/parser/WdlParser.java
  wdl/transforms/biscayne/src/test/cases/afters.wdl
  wdl/transforms/biscayne/src/test/scala/wdl/transforms/biscayne/ast2wdlom/WdlFileToWdlomSpec.scala
  wdl/transforms/draft2/src/main/scala/wdl/transforms/draft2/wdlom2wom/WdlDraft2WomCallNodeMaker.scala
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/ast2wdlom/WdlFileToWdlomSpec.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/AstToCallElement.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/GenericAst.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/linking/graph/LinkedGraphMaker.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/linking/graph/package.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wdl/WdlWriterImpl.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/WorkflowDefinitionElementToWomWorkflowDefinition.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/graph/CallElementToGraphNode.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/graph/IfElementToGraphNode.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/graph/ScatterElementToGraphNode.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/graph/WorkflowGraphElementToGraphNode.scala
  wom/src/main/scala/wom/graph/CallNode.scala
  wom/src/main/scala/wom/graph/GraphNode.scala
  wom/src/main/scala/wom/graph/GraphNodePort.scala
  wom/src/test/scala/wom/graph/ExpressionAsCallInputSpec.scala
  wom/src/test/scala/wom/graph/GraphSpec.scala
  wom/src/test/scala/wom/graph/ScatterNodeSpec.scala
  womtool/src/main/scala/womtool/wom2wdlom/WomToWdlom.scala
  womtool/src/test/resources/validate/biscayne/invalid/after_circle/after_circle.wdl
  womtool/src/test/resources/validate/biscayne/invalid/after_circle/error.txt
  womtool/src/test/resources/validate/biscayne/invalid/bad_after/bad_after.wdl
  womtool/src/test/resources/validate/biscayne/invalid/bad_after/error.txt
  womtool/src/test/resources/validate/biscayne/invalid/bad_task/error.txt
  womtool/src/test/resources/validate/biscayne/valid/afters/afters.wdl
  womtool/src/test/resources/validate/biscayne/valid/afters_and_ifs/afters_and_ifs.wdl
  womtool/src/test/resources/validate/biscayne/valid/afters_and_scatters/afters_and_scatters.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/bad_task/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/importing_omitting_outputs/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/subwf_sub_inputs/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/unexpected_subworkflow_call_input_failure/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/unwanted_task_input/error.txt
Labels: WDL Biscayne, ⭐ Two Thumbs-Up ⭐, 🌲Redwood, 👍Red Thumb Required 🙏

#4517 Relative import doc update
  docs/Imports.md
Labels: Documentation, 🌲Redwood

#4527 Fix bcbio test bcbio_svcall
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/main-svcall-samples.json
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/main-svcall.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/alignment_to_rec.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/batch_for_sv.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/batch_for_variantcall.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/calculate_sv_bins.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/calculate_sv_coverage.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/combine_sample_regions.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/compare_to_rm.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/concat_batch_variantcalls.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/detect_sv.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/get_parallel_regions.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/merge_split_alignments.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/multiqc_summary.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/normalize_sv_coverage.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/pipeline_summary.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/postprocess_alignment.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/postprocess_alignment_to_rec.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/postprocess_variants.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/prep_align_inputs.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/prep_samples.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/prep_samples_to_rec.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/process_alignment.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/qc_to_rec.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/summarize_sv.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/summarize_vc.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/steps/variantcall_batch_region.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/wf-alignment.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/wf-svcall.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/svcall-workflow/wf-variantcall.cwl
Labels: 🌲Redwood

#4532 Fix bcbio test bcbio_somatic
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/main-somatic-samples.json
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/main-somatic.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/alignment_to_rec.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/batch_for_sv.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/batch_for_variantcall.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/calculate_sv_bins.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/calculate_sv_coverage.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/combine_sample_regions.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/compare_to_rm.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/concat_batch_variantcalls.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/detect_sv.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/get_parallel_regions.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/merge_split_alignments.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/multiqc_summary.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/normalize_sv_coverage.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/pipeline_summary.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/postprocess_alignment.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/postprocess_alignment_to_rec.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/postprocess_variants.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/prep_align_inputs.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/prep_samples.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/prep_samples_to_rec.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/process_alignment.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/qc_to_rec.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/summarize_sv.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/summarize_vc.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/steps/variantcall_batch_region.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/wf-svcall.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/somatic-workflow/wf-variantcall.cwl
Labels: 🌲Redwood

#4529 De-CTKS some Array tests.
  build.sbt
  common/src/test/scala/common/assertion/ErrorOrAssertions.scala
  core/src/test/scala/cromwell/util/SampleWdl.scala
  languageFactories/wdl-draft2/src/test/scala/languages.wdl.draft2/ArrayCoercionsSpec.scala
  server/src/test/scala/cromwell/ArrayOfArrayCoercionSpec.scala
  server/src/test/scala/cromwell/ArrayWorkflowSpec.scala
  wdl/model/draft2/src/main/scala/wdl/draft2/model/WdlExpression.scala
Labels: QA Triage, ⭐ Two Thumbs-Up ⭐

#4530 de-CTKS map tests
  centaur/src/main/resources/standardTestCases/map_workflow.test
  centaur/src/main/resources/standardTestCases/map_workflow/map_workflow.wdl
  core/src/test/scala/cromwell/util/SampleWdl.scala
  languageFactories/wdl-draft2/src/test/scala/languages.wdl.draft2/MapWorkflowSpec.scala
  server/src/test/scala/cromwell/MapWorkflowSpec.scala
Labels: QA Triage, ⭐ Two Thumbs-Up ⭐

#4548 Better error messages for cyclic dependencies
  wdl/model/draft2/src/main/scala/wdl/draft2/model/Scope.scala
  wdl/transforms/draft2/src/main/scala/wdl/transforms/draft2/wdlom2wom/WdlDraft2WomGraphMaker.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/linking/graph/LinkedGraphMaker.scala
  womtool/src/test/resources/validate/biscayne/invalid/after_circle/error.txt
  womtool/src/test/resources/validate/wdl_draft2/invalid/cycle/cycle.wdl
  womtool/src/test/resources/validate/wdl_draft2/invalid/cycle/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/cycle/cycle.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/cycle/error.txt
Labels: 🌲Redwood

#4556 Write Papi CI files to a bucket with a TTL.
  centaur/src/main/config/jes-compose.yml.ctmpl
  centaur/src/main/resources/standardTestCases/call_cache_hit_prefixes/call_cache_hit_prefixes_two_roots_empty_hint_papi_first.options
  centaur/src/main/resources/standardTestCases/call_cache_hit_prefixes/call_cache_hit_prefixes_two_roots_empty_hint_papi_second.options
  centaur/src/main/resources/standardTestCases/copy_workflow_outputs/scattered_papi.options
  centaur/src/main/resources/standardTestCases/copy_workflow_outputs/unscattered_papi.options
  centaur/src/main/resources/standardTestCases/copy_workflow_outputs_scattered_papi.test
  centaur/src/main/resources/standardTestCases/copy_workflow_outputs_unscattered_papi.test
  centaur/src/main/resources/standardTestCases/final_call_logs_dir/final_call_logs_dir_jes.options
  centaur/src/main/resources/standardTestCases/final_call_logs_dir_jes.test
  centaur/src/main/resources/standardTestCases/fofn_caching.test
  centaur/src/main/resources/standardTestCases/monitoring_log_papiv1.test
  centaur/src/main/resources/standardTestCases/monitoring_log_papiv2.test
  centaur/src/main/resources/standardTestCases/papi_v2_log/papi_v2_log.wdl
  src/ci/resources/papi_provider_config.inc.conf
Labels: ⭐ Two Thumbs-Up ⭐

#4580 Add config for disabling sam submit whitelist.
  CromIAM/src/main/resources/application.conf
  CromIAM/src/main/scala/cromiam/sam/SamClient.scala
  CromIAM/src/main/scala/cromiam/server/config/CromIamServerConfig.scala
  CromIAM/src/main/scala/cromiam/webservice/CromIamApiService.scala
  CromIAM/src/test/scala/cromiam/sam/SamClientSpec.scala
  CromIAM/src/test/scala/cromiam/webservice/MockClients.scala
Labels: Back With Originator ♻️
