Repository broadinstitute/cromwell, pull requests merged in 2019-06, with the labels that each got.

#5003 Retry jobs that have been killed by a cluster backend. [BA-5669]
  supportedBackends/sfs/src/main/scala/cromwell/backend/impl/sfs/config/ConfigAsyncJobExecutionActor.scala
Labels: External Contributor

#5016 Ensure workflowLogger always gets closed [BA-4826]
  engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala
Labels: External Contributor

#5015 Fix submit-docker to point to the right script in example configuration [BA-5689]
  cromwell.example.backends/cromwell.examples.conf
Labels: External Contributor

#5010 Stackdriver Instrumentation BA-4788
  CHANGELOG.md
  core/src/main/resources/reference.conf
  cromwell.example.backends/cromwell.examples.conf
  docs/developers/Instrumentation.md
  project/Dependencies.scala
  services/src/main/scala/cromwell/services/instrumentation/impl/stackdriver/StackdriverConfig.scala
  services/src/main/scala/cromwell/services/instrumentation/impl/stackdriver/StackdriverInstrumentationServiceActor.scala
  services/src/main/scala/cromwell/services/instrumentation/impl/statsd/StatsDConfig.scala
  services/src/test/scala/cromwell/services/instrumentation/impl/stackdriver/StackdriverConfigSpec.scala
  services/src/test/scala/cromwell/services/instrumentation/impl/stackdriver/StackdriverInstrumentationServiceActorSpec.scala
  services/src/test/scala/cromwell/services/instrumentation/impl/stackdriver/TestStackdriverInstrumentationServiceActor.scala
  services/src/test/scala/cromwell/services/instrumentation/impl/statsd/StatsDConfigSpec.scala
  services/src/test/scala/cromwell/services/instrumentation/impl/statsd/StatsDInstrumentationServiceActorBenchmarkSpec.scala
  services/src/test/scala/cromwell/services/instrumentation/impl/statsd/StatsDInstrumentationServiceActorSpec.scala
Labels: Back With Originator ♻️

#5018 Running dockers for postgres and mariadb during tests BA-5665
  .travis.yml
  core/src/test/resources/application.conf
  engine/src/test/scala/cromwell/engine/workflow/lifecycle/execution/callcaching/CallCachingSlickDatabaseSpec.scala
  engine/src/test/scala/cromwell/engine/workflow/workflowstore/SqlWorkflowStoreSpec.scala
  project/ContinuousIntegration.scala
  scripts/docker-compose-mysql/docker-compose-horicromtal.yml
  services/src/test/scala/cromwell/services/ServicesStoreSpec.scala
  services/src/test/scala/cromwell/services/keyvalue/impl/KeyValueDatabaseSpec.scala
  services/src/test/scala/cromwell/services/metadata/impl/MetadataDatabaseAccessSpec.scala
  src/ci/bin/test.inc.sh
  src/ci/bin/testCentaurEngineUpgradeLocal.sh
  src/ci/bin/testCentaurHoricromtalEngineUpgradePapiV2.sh
  src/ci/bin/testCentaurHoricromtalPapiV2.sh
  src/ci/bin/testCentaurPapiUpgradeNewWorkflowsPapiV1.sh
  src/ci/bin/testCentaurPapiUpgradePapiV1.sh
  src/ci/docker-compose/cromwell-test/docker-setup.sh
  src/ci/docker-compose/docker-compose.yml
  src/ci/docker-compose/mariadb-conf.d/init.cnf
  src/ci/docker-compose/mysql-conf.d/init.cnf
  src/ci/docker-compose/postgresql-initdb.d/init.sh
  src/ci/docker-compose/postgresql-initdb.d/init.sql
  src/ci/resources/build_application.inc.conf
  src/ci/resources/cromwell_database.inc.conf
Labels: Back With Originator ♻️, ⭐ Two Thumbs-Up ⭐

#4900 Add cached-copy localization strategy.
  CHANGELOG.md
  centaur/src/main/resources/standardTestCases/cached_copy/cached_copy.wdl
  docs/backends/HPC.md
  supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystem.scala
  supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystemJobCachingActorHelper.scala
  supportedBackends/sfs/src/test/scala/cromwell/backend/sfs/SharedFileSystemSpec.scala
Labels: External Contributor

#5032 Add summarization metrics [Part I of BA-4781]
  database/sql/src/main/scala/cromwell/database/slick/MetadataSlickDatabase.scala
  database/sql/src/main/scala/cromwell/database/sql/MetadataSqlDatabase.scala
  services/src/main/scala/cromwell/services/instrumentation/CromwellMetric.scala
  services/src/main/scala/cromwell/services/metadata/impl/MetadataDatabaseAccess.scala
  services/src/main/scala/cromwell/services/metadata/impl/MetadataServiceActor.scala
  services/src/main/scala/cromwell/services/metadata/impl/MetadataSummaryRefreshActor.scala
  services/src/main/scala/cromwell/services/metadata/impl/WriteMetadataActor.scala
  services/src/test/scala/cromwell/services/metadata/impl/MetadataDatabaseAccessSpec.scala
Labels: <=== READY FOR REVIEW !!!

#5043 Make cached-copy localization strategy aware of the maximum number of hardlinks. [BA-5748]
  cromwell.example.backends/cromwell.examples.conf
  supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystem.scala
  supportedBackends/sfs/src/test/scala/cromwell/backend/sfs/SharedFileSystemSpec.scala
Labels: External Contributor
