Repository broadinstitute/cromwell, pull requests merged in 2019-02, with the labels that each got.

#4567 Token Queue Logging
  CHANGELOG.md
  core/src/main/resources/reference.conf
  core/src/main/scala/cromwell/core/JobExecutionToken.scala
  docs/cromwell_features/HogFactors.md
  engine/src/main/scala/cromwell/engine/workflow/tokens/JobExecutionTokenDispenserActor.scala
  engine/src/main/scala/cromwell/engine/workflow/tokens/RoundRobinQueueIterator.scala
  engine/src/main/scala/cromwell/engine/workflow/tokens/TokenEventLogger.scala
  engine/src/main/scala/cromwell/engine/workflow/tokens/TokenQueue.scala
  engine/src/main/scala/cromwell/engine/workflow/tokens/UnhoggableTokenPool.scala
  engine/src/main/scala/cromwell/server/CromwellRootActor.scala
  engine/src/test/scala/cromwell/engine/workflow/tokens/JobExecutionTokenDispenserActorSpec.scala
  engine/src/test/scala/cromwell/engine/workflow/tokens/RoundRobinQueueIteratorSpec.scala
  engine/src/test/scala/cromwell/engine/workflow/tokens/TokenQueueSpec.scala
  engine/src/test/scala/cromwell/engine/workflow/tokens/UnhoggableTokenPoolSpec.scala
  engine/src/test/scala/cromwell/engine/workflow/tokens/large/LargeScaleJobExecutionTokenDispenserActorSpec.scala
  engine/src/test/scala/cromwell/engine/workflow/tokens/large/TokenDispenserBenchmark.scala
  project/Dependencies.scala
  server/src/test/scala/cromwell/SimpleWorkflowActorSpec.scala
  server/src/test/scala/cromwell/engine/workflow/SingleWorkflowRunnerActorSpec.scala
  server/src/test/scala/cromwell/engine/workflow/lifecycle/execution/WorkflowExecutionActorSpec.scala
Labels: Logs, needs rebase ⚔, 👍Red Thumb Required 🙏

#4610 Labels query performance improvement
  database/sql/src/main/scala/cromwell/database/slick/tables/WorkflowMetadataSummaryEntryComponent.scala
Labels: 🐦Early Feedback Requested

#4597 alter find command for alpine/busybox compatibility
  backend/src/main/scala/cromwell/backend/standard/StandardAsyncExecutionActor.scala
  centaur/src/main/resources/standardTestCases/docker_alpine.test
  centaur/src/main/resources/standardTestCases/docker_alpine/docker_alpine.options
  centaur/src/main/resources/standardTestCases/docker_alpine/docker_alpine.wdl
Labels: Red team, ⭐ Two Thumbs-Up ⭐

#4617 Workflow validation for labels PATCH goes to summary not metadata.
  database/sql/src/main/scala/cromwell/database/slick/MetadataSlickDatabase.scala
  database/sql/src/main/scala/cromwell/database/slick/tables/WorkflowMetadataSummaryEntryComponent.scala
  database/sql/src/main/scala/cromwell/database/sql/MetadataSqlDatabase.scala
  engine/src/main/scala/cromwell/webservice/routes/CromwellApiService.scala
  engine/src/main/scala/cromwell/webservice/routes/MetadataRouteSupport.scala
  engine/src/main/scala/cromwell/webservice/routes/wes/WesRouteSupport.scala
  engine/src/test/scala/cromwell/webservice/routes/CromwellApiServiceSpec.scala
  engine/src/test/scala/cromwell/webservice/routes/MetadataRouteSupportSpec.scala
  services/src/main/scala/cromwell/services/metadata/MetadataService.scala
  services/src/main/scala/cromwell/services/metadata/impl/MetadataDatabaseAccess.scala
  services/src/main/scala/cromwell/services/metadata/impl/MetadataServiceActor.scala
  services/src/test/scala/cromwell/services/metadata/impl/WriteMetadataActorSpec.scala
Labels: Red team

#4619 Downgrade liquibase version for unknown mariadb AIOOBE
  database/migration/src/main/scala/cromwell/database/migration/liquibase/DiffResultFilter.scala
  project/Dependencies.scala
Labels: Red team

#4631 on-demand init so supertrait initialization doesn't see a null
  services/src/main/scala/cromwell/services/healthmonitor/impl/noop/NoopHealthMonitorServiceActor.scala
Labels: 🐛Bug

#4443 [WDL Biscayne] Removal of 'Object' type
  wdl/transforms/biscayne/src/main/java/wdl/biscayne/parser/WdlParser.java
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/ast2wdlom/AstToNewExpressionElements.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/AstNodeToTypeElement.scala
  womtool/src/test/resources/validate/biscayne/invalid/object_struct/error.txt
  womtool/src/test/resources/validate/biscayne/invalid/object_struct/object_struct.inputs.json
  womtool/src/test/resources/validate/biscayne/invalid/object_struct/object_struct.wdl
  womtool/src/test/resources/validate/biscayne/invalid/object_type/error.txt
  womtool/src/test/resources/validate/biscayne/invalid/object_type/object_type.wdl
  womtool/src/test/resources/validate/biscayne/invalid/read_and_write_object/error.txt
  womtool/src/test/resources/validate/biscayne/invalid/read_and_write_object/read_and_write_object.wdl
  womtool/src/test/resources/validate/biscayne/valid/object_struct/object_struct.inputs.json
  womtool/src/test/resources/validate/biscayne/valid/object_struct/object_struct.wdl
Labels: ⭐ Two Thumbs-Up ⭐, 🌲Redwood

#4593 Fix wes chr21
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/main-wes_chr21_test-samples.json
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/main-wes_chr21_test.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/alignment_to_rec.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/batch_for_ensemble.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/batch_for_sv.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/batch_for_variantcall.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/calculate_sv_bins.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/calculate_sv_coverage.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/combine_calls.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/combine_sample_regions.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/compare_to_rm.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/concat_batch_variantcalls.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/detect_sv.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/get_parallel_regions.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/merge_split_alignments.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/multiqc_summary.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/normalize_sv_coverage.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/pipeline_summary.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/postprocess_alignment.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/postprocess_alignment_to_rec.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/postprocess_variants.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/prep_align_inputs.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/prep_samples.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/prep_samples_to_rec.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/process_alignment.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/qc_to_rec.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/summarize_sv.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/summarize_vc.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/steps/variantcall_batch_region.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/wf-svcall.cwl
  centaur/src/main/resources/integrationTestCases/cwl/bcbio/wes_chr21_test-workflow-gcp/wf-variantcall.cwl
Labels: 🌲Redwood

#4581 Clean up unzipped directories
  CHANGELOG.md
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/materialization/MaterializeWorkflowDescriptorActor.scala
  languageFactories/language-factory-core/src/main/scala/cromwell/languages/util/ImportResolver.scala
Labels: Please re-review now, 🌲Redwood

#4662 Publish only the `-SNAP` docker tag for snapshot sbt dockerBuildAndPush.
  project/Publishing.scala
  project/Version.scala
Labels: Red team

#4666 Fixed HPC docker paths and added centaur test for slurm.
  .travis.yml
  CHANGELOG.md
  CromIAM/src/test/scala/cromiam/webservice/CromIamApiServiceSpec.scala
  backend/src/main/scala/cromwell/backend/BackendWorkflowInitializationActor.scala
  backend/src/main/scala/cromwell/backend/standard/StandardAsyncExecutionActor.scala
  backend/src/main/scala/cromwell/backend/standard/StandardSyncExecutionActor.scala
  backend/src/test/scala/cromwell/backend/BackendWorkflowInitializationActorSpec.scala
  backend/src/test/scala/cromwell/backend/OutputEvaluatorSpec.scala
  backend/src/test/scala/cromwell/backend/standard/callcaching/StandardFileHashingActorSpec.scala
  centaur/src/main/resources/standardTestCases/length/length_slurm_no_docker.options
  centaur/src/main/resources/standardTestCases/length_slurm_no_docker.test
  cloud-nio/cloud-nio-impl-ftp/src/test/scala/cloud/nio/impl/ftp/FtpCloudNioFileSystemProviderSpec.scala
  core/src/main/resources/reference_local_provider_config.inc.conf
  core/src/main/scala/cromwell/core/io/CorePathFunctionSet.scala
  core/src/test/scala/cromwell/core/filesystem/CromwellFileSystemsSpec.scala
  core/src/test/scala/cromwell/core/path/PathBuilderFactorySpec.scala
  core/src/test/scala/cromwell/util/SampleWdl.scala
  cwl/src/main/scala/cwl/MyriadInputTypeToWomType.scala
  cwl/src/main/scala/cwl/MyriadOutputTypeToWomType.scala
  cwl/src/main/scala/cwl/Tool.scala
  cwl/src/main/scala/cwl/Workflow.scala
  cwl/src/test/scala/cwl/ExportCwlSamplesSpec.scala
  cwl/src/test/scala/cwl/WomValueJsonFormatter.scala
  docs/backends/HTcondor.md
  docs/backends/SGE.md
  engine/src/main/scala/cromwell/engine/EngineIoFunctions.scala
  engine/src/main/scala/cromwell/engine/io/nio/NioFlow.scala
  engine/src/main/scala/cromwell/jobstore/JobResultJsonFormatter.scala
  engine/src/main/scala/cromwell/webservice/WorkflowJsonSupport.scala
  filesystems/sra/src/main/scala/cromwell/filesystems/sra/SraPathBuilder.scala
  server/src/test/scala/cromwell/engine/EngineFunctionsSpec.scala
  server/src/test/scala/cromwell/jobstore/JobStoreWriterSpec.scala
  services/src/test/scala/cromwell/services/metadata/impl/pubsub/PubSubMetadataServiceActorSpec.scala
  src/ci/bin/testCentaurSlurm.sh
  src/ci/bin/test_slurm.inc.sh
  src/ci/resources/slurm_application.conf
  supportedBackends/google/pipelines/common/src/test/scala/cromwell/backend/google/pipelines/common/PipelinesApiTestConfig.scala
  supportedBackends/google/pipelines/common/src/test/scala/cromwell/backend/google/pipelines/common/api/PipelinesApiRequestManagerSpec.scala
  supportedBackends/sfs/src/main/scala/cromwell/backend/impl/sfs/config/ConfigAsyncJobExecutionActor.scala
  supportedBackends/sfs/src/main/scala/cromwell/backend/impl/sfs/config/ConfigConstants.scala
  supportedBackends/sfs/src/main/scala/cromwell/backend/impl/sfs/config/ConfigWdlNamespace.scala
  wdl/model/draft2/src/main/scala/wdl/draft2/model/examples/ex2.scala
  wdl/model/draft2/src/main/scala/wdl/draft2/model/examples/ex3.scala
  wdl/model/draft2/src/main/scala/wdl/draft2/model/expression/WdlFunctions.scala
  wdl/model/draft2/src/main/scala/wdl/draft2/model/expression/WdlStandardLibraryFunctions.scala
  wdl/model/draft2/src/main/scala/wdl/draft2/model/types/WdlFlavoredWomType.scala
  wdl/model/draft2/src/test/scala/wdl/expression/ValueEvaluatorSpec.scala
  wdl/model/draft2/src/test/scala/wdl/expression/WdlStandardLibraryFunctionsSpec.scala
  wom/src/main/scala/wom/expression/NoIoFunctionSet.scala
  wom/src/main/scala/wom/types/WomTypeJsonFormatter.scala
  wom/src/main/scala/wom/values/WomValue.scala
  womtool/src/test/scala/womtool/SampleWdl.scala
Labels: Red team
