Repository broadinstitute/cromwell, pull requests merged in 2019-11, with the labels that each got.

#5217 Validate call-caching config once instead of per-workflow
  engine/src/main/scala/cromwell/engine/workflow/WorkflowActor.scala
  engine/src/main/scala/cromwell/engine/workflow/WorkflowManagerActor.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/materialization/MaterializeWorkflowDescriptorActor.scala
  engine/src/main/scala/cromwell/server/CromwellRootActor.scala
  engine/src/test/scala/cromwell/engine/workflow/lifecycle/CachingConfigSpec.scala
  engine/src/test/scala/cromwell/engine/workflow/lifecycle/ValidatingCachingConfigSpec.scala
  engine/src/test/scala/cromwell/engine/workflow/lifecycle/ValidatingCallCachingModeSpec.scala
  server/src/test/scala/cromwell/SimpleWorkflowActorSpec.scala
  server/src/test/scala/cromwell/engine/WorkflowManagerActorSpec.scala
  server/src/test/scala/cromwell/engine/workflow/WorkflowActorSpec.scala
  server/src/test/scala/cromwell/engine/workflow/WorkflowDescriptorBuilderForSpecs.scala
  server/src/test/scala/cromwell/engine/workflow/lifecycle/MaterializeWorkflowDescriptorActorSpec.scala
Labels: Community Contribution

#5258 Reading bytes from file stream without unnecessary cast to chars [BA-6097]
  core/src/main/scala/cromwell/core/path/EvenBetterPathMethods.scala
Labels: ⭐ Two Thumbs-Up ⭐

#5255 IoActor bitesize document [BA-6078]
  docs/developers/bitesize/IoActor/IoActor.md
  docs/developers/bitesize/IoActor/IoActor_basic_hierarchy.png
  docs/developers/bitesize/IoActor/IoActor_message_processing_graph.png
  mkdocs.yml
Labels: ⭐ Two Thumbs-Up ⭐

#5250 changed globLinkCommand to use soft instead of hard links [BA-6089]
  cromwell.example.backends/LocalExample.conf
  cromwell.example.backends/cromwell.examples.conf
Labels: Affects Core Features, Community Contribution

#5272 Configurable Carbonite freeze scanning parameters [BA-6109]
  cromwell.example.backends/cromwell.examples.conf
  hybridCarboniteMetadataService/src/main/scala/cromwell/services/metadata/hybridcarbonite/CarboniteWorkerActor.scala
  hybridCarboniteMetadataService/src/main/scala/cromwell/services/metadata/hybridcarbonite/HybridCarboniteConfig.scala
  hybridCarboniteMetadataService/src/test/scala/cromwell/services/metadata/hybridcarbonite/HybridCarboniteConfigSpec.scala
  src/ci/resources/papi_v2_application.conf
Labels: 🚧BLOCKS RELEASE🚧

#5295 [PAPIv2] Delocalize detritusOutputParameters before jobOutputParameters [BA-6112]
  backend/src/main/scala/cromwell/backend/standard/StandardAsyncExecutionActor.scala
  centaur/src/main/resources/standardTestCases/retry_with_more_memory.test
  centaur/src/main/resources/standardTestCases/retry_with_more_memory/retry_with_more_memory.wdl
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/PipelinesApiAsyncBackendJobExecutionActor.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/api/PipelinesApiRequestFactory.scala
  supportedBackends/google/pipelines/v2alpha1/src/main/resources/gcs_transfer.sh
Labels: 🚧BLOCKS RELEASE🚧
