Repository broadinstitute/cromwell, pull requests merged in 2019-04, with the labels that each got.

#4776 Add example akka config to avoid metadata timeout issue
  cromwell.example.backends/cromwell.examples.conf
  cromwell.examples.conf
Labels: External Contributor

#4778 Skip failing cron tests for AWS
  src/ci/bin/testCentaurAws.sh
Labels: Red team

#4789 The Great Escape
  CHANGELOG.md
  wdl/transforms/biscayne/src/test/cases/biscayne_escaping.wdl
  wdl/transforms/biscayne/src/test/scala/wdl/transforms/biscayne/ast2wdlom/WdlFileToWdlomSpec.scala
  wdl/transforms/draft3/src/main/java/wdl/draft3/parser/WdlParser.java
  wdl/transforms/draft3/src/test/cases/string_escaping.wdl
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/ast2wdlom/WdlFileToWdlomSpec.scala
Labels: 🌲Redwood

#4797 Ensure in containers tutorial, Singularity container name is valid
  docs/tutorials/Containers.md
Labels: External Contributor

#4671 Programmer error and logging in PAPI request manager
  core/src/test/scala/cromwell/util/AkkaTestUtil.scala
  engine/src/test/scala/cromwell/engine/workflow/tokens/TestTokenGrabbingActor.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/PipelinesApiBackendSingletonActor.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/api/PipelinesApiRequestManager.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/api/PipelinesApiRequestWorker.scala
  supportedBackends/google/pipelines/common/src/test/scala/cromwell/backend/google/pipelines/common/api/PipelinesApiRequestManagerSpec.scala
Labels: Red team, 🌲Redwood

#4804 Fix packed CWL bug
  CHANGELOG.md
  centaur/src/main/resources/standardTestCases/cwl_import_type.test
  centaur/src/main/resources/standardTestCases/cwl_import_type/capture_kit.yml
  centaur/src/main/resources/standardTestCases/cwl_import_type/test_wf.cwl
  centaur/src/main/resources/standardTestCases/cwl_import_type/test_wf_inputs.json
  centaur/src/main/resources/standardTestCases/cwl_import_type/touch.cwl
  centaur/src/main/resources/standardTestCases/cwl_import_type_packed.test
  centaur/src/main/resources/standardTestCases/cwl_import_type_packed/test_pack.cwl
  centaur/src/main/resources/standardTestCases/cwl_import_type_packed/test_wf_inputs.json
  cwl/src/main/scala/cwl/model.scala
Labels: 🌲Redwood

#4812 Horicromtal engine upgrade Centaur testing with docker-compose.
  .travis.yml
  src/ci/bin/test.inc.sh
  src/ci/bin/testCentaurHoricromtalEngineUpgradePapiV2.sh
  src/ci/resources/centaur_application_horicromtal.conf
Labels: <=== READY FOR REVIEW !!!

#4815 Fix Issue1641 -> allow for a flattened output directory
  centaur/src/main/resources/standardTestCases/relative_output_paths.test
  centaur/src/main/resources/standardTestCases/relative_output_paths/options.json
  centaur/src/main/resources/standardTestCases/relative_output_paths/workflow_output_paths.wdl
  centaur/src/main/resources/standardTestCases/relative_output_paths_colliding.test
  centaur/src/main/resources/standardTestCases/relative_output_paths_colliding/options.json
  centaur/src/main/resources/standardTestCases/relative_output_paths_colliding/workflow_output_paths_colliding.wdl
  centaur/src/main/resources/standardTestCases/standard_output_paths_colliding_prevented.test
  centaur/src/main/resources/standardTestCases/standard_output_paths_colliding_prevented/options.json
  centaur/src/main/resources/standardTestCases/standard_output_paths_colliding_prevented/workflow_output_paths_colliding.wdl
  core/src/main/scala/cromwell/core/WorkflowOptions.scala
  docs/wf_options/Overview.md
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/finalization/CopyWorkflowOutputsActor.scala
Labels: External Contributor

#4837 Log workflow IDs and counts if metadata fails to be written
  services/src/main/scala/cromwell/services/metadata/impl/WriteMetadataActor.scala
Labels: 🚧BLOCKS RELEASE🚧

#4847 fix json escaping for real
  release/release_workflow.wdl
Labels: 🚧BLOCKS RELEASE🚧

#4858 [develop] Fix AWS "filename too long"
  filesystems/s3/src/main/java/org/lerch/s3fs/S3Channel.java
  filesystems/s3/src/main/java/org/lerch/s3fs/S3FileChannel.java
  filesystems/s3/src/main/java/org/lerch/s3fs/S3SeekableByteChannel.java
  src/ci/bin/testCentaurAws.sh
Labels: AWS Backend

#4853 [develop] Fix aliased task separation
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchJob.scala
Labels: AWS Backend

#4854 [develop] Fix AWS continueOnReturnCode (#4813)
  src/ci/bin/testCentaurAws.sh
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchJob.scala
Labels: AWS Backend

#4865 docker compatibility for AWS Batch
  docs/cromwell_features/CallCaching.md
Labels: AWS Backend

#4883 Mlc fix horicromtal engine upgrade
  scripts/docker-compose-mysql/docker-compose-horicromtal.yml
  src/ci/bin/testCentaurHoricromtalEngineUpgradePapiV2.sh
  src/ci/bin/testCentaurHoricromtalPapiV2.sh
  src/ci/resources/horicromtal_application.conf
Labels: HIGH PRIORITY

#4785 Add config option to shutdown cromwell when unable to write heartbeats.
  CHANGELOG.md
  core/src/main/resources/reference.conf
  core/src/test/scala/cromwell/core/TestKitSuite.scala
  database/sql/src/main/scala/cromwell/database/slick/WorkflowStoreSlickDatabase.scala
  database/sql/src/main/scala/cromwell/database/sql/WorkflowStoreSqlDatabase.scala
  docs/Configuring.md
  engine/src/main/scala/cromwell/engine/CromwellTerminator.scala
  engine/src/main/scala/cromwell/engine/workflow/SingleWorkflowRunnerActor.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/InMemoryWorkflowStore.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/SqlWorkflowStore.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/WorkflowHeartbeatConfig.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/WorkflowStore.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/WorkflowStoreAccess.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/WorkflowStoreActor.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/WorkflowStoreCoordinatedAccessActor.scala
  engine/src/main/scala/cromwell/engine/workflow/workflowstore/WorkflowStoreHeartbeatWriteActor.scala
  engine/src/main/scala/cromwell/server/CromwellRootActor.scala
  engine/src/main/scala/cromwell/server/CromwellServer.scala
  engine/src/main/scala/cromwell/server/CromwellSystem.scala
  engine/src/test/scala/cromwell/engine/MockCromwellTerminator.scala
  engine/src/test/scala/cromwell/engine/workflow/workflowstore/SqlWorkflowStoreSpec.scala
  engine/src/test/scala/cromwell/engine/workflow/workflowstore/WorkflowHeartbeatConfigSpec.scala
  engine/src/test/scala/cromwell/engine/workflow/workflowstore/WorkflowStoreCoordinatedAccessActorSpec.scala
  engine/src/test/scala/cromwell/engine/workflow/workflowstore/WorkflowStoreHeartbeatWriteActorSpec.scala
  server/src/main/scala/cromwell/CromwellEntryPoint.scala
  server/src/test/scala/cromwell/CromwellTestKitSpec.scala
  server/src/test/scala/cromwell/engine/WorkflowManagerActorSpec.scala
  server/src/test/scala/cromwell/engine/WorkflowStoreActorSpec.scala
  server/src/test/scala/cromwell/engine/workflow/SingleWorkflowRunnerActorSpec.scala
  server/src/test/scala/cromwell/subworkflowstore/SubWorkflowStoreSpec.scala
  services/src/main/scala/cromwell/services/instrumentation/InstrumentedBatchActor.scala
Labels: Back With Originator ♻️, ⛔ DO NOT MERGE ⛔

#4876 [develop] Ensure HealthMonitorServiceActor can initialize without google config
  services/src/main/scala/cromwell/services/healthmonitor/impl/workbench/WorkbenchHealthMonitorServiceActor.scala
  services/src/test/scala/cromwell/services/healthmonitor/HealthMonitorServiceActorSpec.scala
Labels: 🤕Hotfix Candidate

#4889 Don't pass on Sam Conflict [38_hotfix]
  CromIAM/src/main/scala/cromiam/sam/SamClient.scala
Labels: Back With Originator ♻️

#4872 Log warnings for long running jobs
  CHANGELOG.md
  backend/src/main/scala/cromwell/backend/SlowJobWarning.scala
  backend/src/main/scala/cromwell/backend/async/AsyncBackendJobExecutionActor.scala
  backend/src/main/scala/cromwell/backend/backend.scala
  backend/src/main/scala/cromwell/backend/standard/StandardAsyncExecutionActor.scala
  cromwell.example.backends/AWS.conf
  cromwell.example.backends/LSF.conf
  cromwell.example.backends/PAPIv2.conf
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/PipelinesApiAsyncBackendJobExecutionActor.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/PipelinesApiConfiguration.scala
Labels: Please re-review now

#4823 Adopt newest CWL conformance
  centaur/src/main/resources/standardTestCases/cwl_output_json/cwl_output_json.inputs
  centaurCwlRunner/src/main/scala/centaur/cwl/OutputManipulator.scala
  centaurCwlRunner/src/test/resources/application.conf
  centaurCwlRunner/src/test/scala/CloudPreprocessorSpec.scala
  src/ci/bin/test.inc.sh
  src/ci/bin/testConformanceLocal.sh
  src/ci/bin/testConformancePapiV2.sh
  src/ci/resources/local_conformance_expected_failures.txt
  src/ci/resources/papi_v2_conformance_expected_failures.txt
  src/ci/resources/tesk_conformance_expected_failures.txt
Labels: CWL, Please re-review now

#4890 Create CITATION.md
  CITATION.md
Labels: External Contributor

#4888 Don't pass on Sam Conflict [39_hotfix]
  CromIAM/src/main/scala/cromiam/sam/SamClient.scala
Labels: Back With Originator ♻️

#4887 Don't pass on Sam Conflict [40_hotfix]
  CromIAM/src/main/scala/cromiam/sam/SamClient.scala
Labels: Back With Originator ♻️

#4886 Don't pass on Sam Conflict [develop]
  CromIAM/src/main/scala/cromiam/sam/SamClient.scala
  CromIAM/src/test/scala/cromiam/sam/SamClientSpec.scala
  CromIAM/src/test/scala/cromiam/webservice/MockClients.scala
  CromIAM/src/test/scala/cromiam/webservice/QuerySupportSpec.scala
  CromIAM/src/test/scala/cromiam/webservice/SubmissionSupportSpec.scala
Labels: Sprint 1 Planned
