Repository broadinstitute/cromwell, pull requests merged in 2019-09, with the labels that each got.

#5143 Handle WomCoproductValue in inputs
  centaur/src/main/resources/standardTestCases/cwl_input_typearray.test
  centaur/src/main/resources/standardTestCases/cwl_input_typearray/input.txt
  centaur/src/main/resources/standardTestCases/cwl_input_typearray/input_typearray.cwl
  centaur/src/main/resources/standardTestCases/cwl_input_typearray/input_typearray.yml
  cwl/src/main/scala/cwl/CwlExpressionCommandPart.scala
  wom/src/main/scala/wom/WomFileMapper.scala
Labels: Affects Core Features, Community Contribution

#5148 BCS Call caching optimization [BA-5965]
  docs/backends/BCS.md
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/BcsClusterIdOrConfiguration.scala
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/BcsJob.scala
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/BcsRuntimeAttributes.scala
  supportedBackends/bcs/src/test/scala/cromwell/backend/impl/bcs/BcsJobSpec.scala
  supportedBackends/bcs/src/test/scala/cromwell/backend/impl/bcs/BcsRuntimeAttributesSpec.scala
  supportedBackends/bcs/src/test/scala/cromwell/backend/impl/bcs/BcsTestUtilSpec.scala
Labels: Community Contribution

#5151 Update Slurm.md sbatch command syntax BA-5973
  docs/backends/SLURM.md
Labels: Community Contribution

#5070 AWS EFS support BA-5827
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchAsyncBackendJobExecutionActor.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchAttributes.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchBackendInitializationData.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchBackendLifecycleActorFactory.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchConfiguration.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchExpressionFunctions.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchFinalizationActor.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchInitializationActor.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchJob.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchJobCachingActorHelper.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchJobDefinition.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchRuntimeAttributes.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchWorkflowPaths.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/callcaching/AwsBatchBackendCacheHitCopyingActor.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/callcaching/AwsBatchBackendFileHashingActor.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/io/AwsBatchVolume.scala
  supportedBackends/aws/src/test/scala/cromwell/backend/impl/aws/AwsBatchConfigurationSpec.scala
Labels: Affects Core Features, Awaiting user info, Community Contribution

#5125 Client side filtering of metadata for sanity's sake [BA-5996]
  database/sql/src/main/scala/cromwell/database/slick/MetadataSlickDatabase.scala
  database/sql/src/main/scala/cromwell/database/slick/tables/MetadataEntryComponent.scala
Labels: Please re-review now

#5184 Add configuration for volcano, a batch system on k8s. [BA-6011]
  cromwell.example.backends/volcano.conf
  docs/backends/Volcano.md
Labels: Community Contribution

#5097 AWS Batch with CWL: did not localize cwl.inputs.json [BA-4586]
  backend/src/main/scala/cromwell/backend/standard/StandardAsyncExecutionActor.scala
  centaur/src/main/resources/standardTestCases/ad_hoc_file_test.aws.test
  centaur/src/main/resources/standardTestCases/ad_hoc_file_test/cwl-test.cwl
  centaur/src/main/resources/standardTestCases/ad_hoc_file_test/workflow.cwl
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchAsyncBackendJobExecutionActor.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/PipelinesApiAsyncBackendJobExecutionActor.scala
Labels: Affects Core Features, Community Contribution

#5170 TODO Add ARN validation [BA-5994]
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchRuntimeAttributes.scala
  supportedBackends/aws/src/test/scala/cromwell/backend/impl/aws/ArnValidationSpec.scala
  supportedBackends/aws/src/test/scala/cromwell/backend/impl/aws/AwsBatchAsyncBackendJobExecutionActorSpec.scala
  supportedBackends/aws/src/test/scala/cromwell/backend/impl/aws/AwsBatchRuntimeAttributesSpec.scala
  supportedBackends/aws/src/test/scala/cromwell/backend/impl/aws/AwsBatchTestConfig.scala
Labels: Community Contribution
