Repository broadinstitute/cromwell, pull requests merged in 2019-12, with the labels that each got.

#5278 Correctly handle retries when both `preemptible` and `maxRetries` runtime parameters are set [BA-6102]
  backend/src/main/scala/cromwell/backend/async/AsyncBackendJobExecutionActor.scala
  backend/src/main/scala/cromwell/backend/async/ExecutionHandle.scala
  backend/src/main/scala/cromwell/backend/async/KnownJobFailureException.scala
  backend/src/main/scala/cromwell/backend/standard/StandardAsyncExecutionActor.scala
  centaur/src/main/resources/standardTestCases/papi_preemptible_and_max_retries.test
  centaur/src/main/resources/standardTestCases/papi_preemptible_and_max_retries/papi_preemptible_and_max_retries.wdl
  supportedBackends/bcs/src/main/scala/cromwell/backend/impl/bcs/BcsAsyncBackendJobExecutionActor.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/PipelinesApiAsyncBackendJobExecutionActor.scala
  supportedBackends/google/pipelines/common/src/test/scala/cromwell/backend/google/pipelines/common/PipelinesApiAsyncBackendJobExecutionActorSpec.scala
  supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystemAsyncJobExecutionActor.scala
  supportedBackends/tes/src/main/scala/cromwell/backend/impl/tes/TesAsyncBackendJobExecutionActor.scala
Labels: 🚧BLOCKS RELEASE🚧

#5308 Updated swagger-ui version to 3.23.11 [BA-6120]
  CromIAM/src/main/scala/cromiam/webservice/CromIamApiService.scala
  CromIAM/src/test/scala/cromiam/webservice/SwaggerUiHttpServiceSpec.scala
  engine/src/test/scala/cromwell/webservice/SwaggerUiHttpServiceSpec.scala
  project/Dependencies.scala
Labels: ⭐ Two Thumbs-Up ⭐

#5299 Patch build docs and add a warning to womtool doc about graph failing on 1.0
  docs/WOMtool.md
  docs/developers/Building.md
Labels: Documentation, UserSupport ❤️, womtool

#5296 Add slow job warning for centaur PAPI jobs [BA-6145]
  backend/src/main/scala/cromwell/backend/backend.scala
  centaur/src/main/scala/centaur/test/Test.scala
  centaur/src/main/scala/centaur/test/formulas/TestFormulas.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/WorkflowExecutionActor.scala
  hybridCarboniteMetadataService/src/main/scala/cromwell/services/metadata/hybridcarbonite/HybridCarboniteConfig.scala
  server/src/main/resources/logback.xml
  src/ci/resources/centaur_application_horicromtal.conf
  src/ci/resources/papi_provider_config.inc.conf
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchAttributes.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/PipelinesApiConfigurationAttributes.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/api/PipelinesApiRequestManager.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/api/PipelinesApiRequestWorker.scala
  supportedBackends/google/pipelines/common/src/test/scala/cromwell/backend/google/pipelines/common/api/PipelinesApiRequestManagerSpec.scala
Labels: ⭐ Two Thumbs-Up ⭐

#5320 Documented the use of a file-based database
  CHANGELOG.md
  docs/Configuring.md
Labels: Community Contribution

#5323 fix markdown formatting errors.
  docs/Configuring.md
Labels: Community Contribution
