Repository broadinstitute/cromwell, pull requests merged in 2019-03, with the labels that each got.

#4635 Create documentation for Cromwell and containers
  docs/tutorials/Containers.md
  mkdocs.yml
Labels: <=== READY FOR REVIEW !!!

#4624 Pass through Cromwell & Sam HTTP errors to Cromiam.
  CHANGELOG.md
  CromIAM/src/main/scala/cromiam/cromwell/CromwellClient.scala
  CromIAM/src/main/scala/cromiam/instrumentation/CromIamInstrumentation.scala
  CromIAM/src/main/scala/cromiam/sam/SamClient.scala
  CromIAM/src/main/scala/cromiam/webservice/CromIamApiService.scala
  CromIAM/src/main/scala/cromiam/webservice/EngineRouteSupport.scala
  CromIAM/src/main/scala/cromiam/webservice/QuerySupport.scala
  CromIAM/src/main/scala/cromiam/webservice/SubmissionSupport.scala
  CromIAM/src/test/scala/cromiam/cromwell/CromwellClientSpec.scala
  CromIAM/src/test/scala/cromiam/sam/SamClientSpec.scala
  CromIAM/src/test/scala/cromiam/webservice/CromIamApiServiceSpec.scala
  CromIAM/src/test/scala/cromiam/webservice/EngineRouteSupportSpec.scala
  CromIAM/src/test/scala/cromiam/webservice/MockClients.scala
  CromIAM/src/test/scala/cromiam/webservice/QuerySupportSpec.scala
  CromIAM/src/test/scala/cromiam/webservice/SubmissionSupportSpec.scala
  CromIAM/src/test/scala/cromiam/webservice/SwaggerServiceSpec.scala
  CromIAM/src/test/scala/cromiam/webservice/SwaggerUiHttpServiceSpec.scala
  centaur/src/it/scala/centaur/CentaurTestSuite.scala
  centaur/src/main/scala/centaur/api/CentaurCromwellClient.scala
  cromwellApiClient/src/main/scala/cromwell/api/CromwellClient.scala
  cromwellApiClient/src/main/scala/cromwell/api/model/CromwellFailedResponseException.scala
  cromwellApiClient/src/main/scala/cromwell/api/model/package.scala
  cromwellApiClient/src/test/scala/cromwell/api/CromwellResponseFailedSpec.scala
  engine/src/main/scala/cromwell/webservice/WebServiceUtils.scala
  engine/src/test/scala/cromwell/webservice/routes/CromwellApiServiceSpec.scala
  engine/src/test/scala/cromwell/webservice/routes/MetadataRouteSupportSpec.scala
  project/Dependencies.scala
  server/src/main/scala/cromwell/CromwellEntryPoint.scala
Labels: Red team

#4632 noop health check by default
  CHANGELOG.md
  core/src/main/resources/reference.conf
Labels: Red team

#4704 Phil's cpuPlatform runtime attribute + a Centaur test
  centaur/src/main/resources/standardTestCases/papi_cpu_platform.test
  centaur/src/main/resources/standardTestCases/papi_cpu_platform/papi_cpu_platform.wdl
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/PipelinesApiRuntimeAttributes.scala
  supportedBackends/google/pipelines/common/src/test/scala/cromwell/backend/google/pipelines/common/PipelinesApiRuntimeAttributesSpec.scala
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/GenomicsFactory.scala
  wom/src/main/scala/wom/RuntimeAttributes.scala
Labels: Red team

#4695 Add key/value index for custom labels.
  database/migration/src/main/resources/metadata_changesets/custom_label_entry_key_value_index.xml
  database/migration/src/main/resources/sql_metadata_changelog.xml
  database/sql/src/main/scala/cromwell/database/slick/tables/CustomLabelEntryComponent.scala
Labels: Red team

#4639 [Biscayne] WDL 'None' literal
  centaur/src/main/resources/standardTestCases/none_literal.test
  centaur/src/main/resources/standardTestCases/none_literal/none_literal.wdl
  wdl/model/draft3/src/main/scala/wdl/model/draft3/elements/ExpressionElement.scala
  wdl/transforms/biscayne/src/main/java/wdl/biscayne/parser/WdlParser.java
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/consumed/BiscayneExpressionValueConsumers.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/consumed/consumed.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/types/types.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/values/BiscayneValueEvaluators.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/values/values.scala
  wdl/transforms/biscayne/src/test/scala/wdl/transforms/biscayne/Ast2WdlomSpec.scala
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/ast2wdlom/Ast2WdlomSpec.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/AstNodeToExpressionElement.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/linking/expression/types/LiteralEvaluators.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wdl/WdlWriterImpl.scala
  wom/src/main/scala/wom/types/WomArrayType.scala
  wom/src/main/scala/wom/types/WomType.scala
  womtool/src/test/resources/validate/biscayne/valid/use_nones/use_nones.wdl
  womtool/src/test/resources/validate/wdl_draft3/invalid/use_nones/error.txt
  womtool/src/test/resources/validate/wdl_draft3/invalid/use_nones/use_nones.wdl
Labels: 🌲Redwood

#4702 Hand rolled query SQL
  database/sql/src/main/scala/cromwell/database/slick/MetadataSlickDatabase.scala
  database/sql/src/main/scala/cromwell/database/slick/tables/WorkflowMetadataSummaryEntryComponent.scala
Labels: Please re-review now

#4654 Refactor CAJEA pollStatus logic
  supportedBackends/sfs/src/main/scala/cromwell/backend/impl/sfs/config/ConfigAsyncJobExecutionActor.scala
  supportedBackends/sfs/src/main/scala/cromwell/backend/sfs/SharedFileSystemAsyncJobExecutionActor.scala
Labels: Red team, 🌲Redwood

#4661 Enhance map errors
  wom/src/main/scala/wom/values/WomMap.scala
  wom/src/test/scala/wom/types/WomMapTypeSpec.scala
Labels: 🌲Redwood

#4727 Make sure importing from file:// is not a horrible danger
  centaur/src/main/resources/standardTestCases/import_passwd_url.test
  centaur/src/main/resources/standardTestCases/import_passwd_url/import_passwd_url.wdl
Labels: 🌲Redwood

#4744 Release WDL updates
  release/release_inputs.json
  release/release_workflow.wdl
Labels: Red team

#4729 Meta section in draft-3
  wdl/transforms/draft3/src/test/cases/task_with_metas2.wdl
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/ast2wdlom/WdlFileToWdlomSpec.scala
  wdl/transforms/draft3/src/test/scala/wdl/draft3/transforms/wdlom2wom/WdlFileToWomSpec.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/TaskDefinitionElementToWomTaskDefinition.scala
Labels: Red team, 🌲Redwood

#4660 Expect some progress in centaur tests
  centaur/src/main/scala/centaur/test/CentaurTestException.scala
  centaur/src/main/scala/centaur/test/Test.scala
  centaur/src/main/scala/centaur/test/formulas/TestFormulas.scala
Labels: 🌲Redwood

#4748 instructions for unbreaking tests on Local backend
  centaur/src/main/resources/standardTestCases/call_cache_capoeira_local.test
  centaur/src/main/resources/standardTestCases/draft3_call_cache_capoeira_local.test
  centaur/src/main/resources/standardTestCases/long_cmd.test
Labels: Red team

#4749 AWS backend: sleep 60 secs and retry 5 times if download or upload fails
  supportedBackends/aws/src/main/resources/ecs-proxy/proxy
Labels: Red team

#4743 Update AWS Batch example conf to reflect our docs
  cromwell.example.backends/AWS.conf
Labels: Red team

#4747 Remove leading slash from S3Path's pathWithoutSchema
  filesystems/s3/src/main/scala/cromwell/filesystems/s3/S3PathBuilder.scala
  filesystems/s3/src/main/scala/cromwell/filesystems/s3/batch/S3BatchIoCommand.scala
  src/ci/bin/testCentaurAws.sh
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchAsyncBackendJobExecutionActor.scala
Labels: Red team

#4754 Fix womtool endpoint to understand nonempty arrays
  services/src/main/scala/cromwell/services/womtool/models/WomTypeJsonSupport.scala
  services/src/test/resources/describe/wdl_1_0/arrays/description.json
  services/src/test/resources/describe/wdl_1_0/arrays/workflow.wdl
  services/src/test/resources/describe/wdl_draft_2/arrays/description.json
  services/src/test/resources/describe/wdl_draft_2/arrays/workflow.wdl
Labels: WaaS, 🌲Redwood, 👍Red Thumb Required 🙏

#4758 Stop flipping rows and columns in write_map() output
  CHANGELOG.md
  centaur/src/main/resources/standardTestCases/draft3_read_write_functions_local.test
  centaur/src/main/resources/standardTestCases/draft3_read_write_functions_papi.test
  centaur/src/main/resources/standardTestCases/wdl_draft3/read_write_functions/read_write_functions.wdl
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/linking/expression/values/EngineFunctionEvaluators.scala
Labels: 🌲Redwood

#4766 Embiggen the Centaur test suite for AWS backend
  src/ci/bin/testCentaurAws.sh
Labels: Red team

#4765 Add TMiguelT's long file name test to Centaur
  centaur/src/main/resources/standardTestCases/file_name_too_long.test
  centaur/src/main/resources/standardTestCases/file_name_too_long/a.wdl
  centaur/src/main/resources/standardTestCases/file_name_too_long/b.wdl
  centaur/src/main/resources/standardTestCases/file_name_too_long/c.wdl
  centaur/src/main/resources/standardTestCases/file_name_too_long/d.wdl
  src/ci/bin/testCentaurAws.sh
Labels: Red team

#4764 /describe endpoint: meta, parameter_meta, images
  engine/src/test/scala/cromwell/webservice/routes/CromwellApiServiceSpec.scala
  engine/src/test/scala/cromwell/webservice/routes/WomtoolRouteSupportSpec.scala
  services/src/main/scala/cromwell/services/womtool/models/WorkflowDescription.scala
  services/src/test/resources/describe/wdl_1_0/arrays/description.json
  services/src/test/resources/describe/wdl_1_0/basics/description.json
  services/src/test/resources/describe/wdl_1_0/basics/workflow.wdl
  services/src/test/resources/describe/wdl_1_0/cant_parse_draft_2/description.json
  services/src/test/resources/describe/wdl_1_0/empty_workflow/description.json
  services/src/test/resources/describe/wdl_1_0/invalid_workflow/description.json
  services/src/test/resources/describe/wdl_1_0/name_from_task/description.json
  services/src/test/resources/describe/wdl_1_0/name_from_task/workflow.wdl
  services/src/test/resources/describe/wdl_1_0/name_from_workflow/description.json
  services/src/test/resources/describe/wdl_1_0/name_from_workflow/workflow.wdl
  services/src/test/resources/describe/wdl_1_0/name_none_from_tasks/description.json
  services/src/test/resources/describe/wdl_1_0/name_none_from_tasks/workflow.wdl
  services/src/test/resources/describe/wdl_1_0/nested_map/description.json
  services/src/test/resources/describe/wdl_1_0/objects/description.json
  services/src/test/resources/describe/wdl_1_0/whitespace_workflow/description.json
  services/src/test/resources/describe/wdl_draft_2/arrays/description.json
  services/src/test/resources/describe/wdl_draft_2/basics/description.json
  services/src/test/resources/describe/wdl_draft_2/basics/workflow.wdl
  services/src/test/resources/describe/wdl_draft_2/cant_parse_1_0/description.json
  services/src/test/resources/describe/wdl_draft_2/empty_workflow/description.json
  services/src/test/resources/describe/wdl_draft_2/invalid_workflow/description.json
  services/src/test/resources/describe/wdl_draft_2/name_from_task/description.json
  services/src/test/resources/describe/wdl_draft_2/name_from_task/workflow.wdl
  services/src/test/resources/describe/wdl_draft_2/name_from_workflow/description.json
  services/src/test/resources/describe/wdl_draft_2/name_from_workflow/workflow.wdl
  services/src/test/resources/describe/wdl_draft_2/name_none_from_tasks/description.json
  services/src/test/resources/describe/wdl_draft_2/name_none_from_tasks/workflow.wdl
  services/src/test/resources/describe/wdl_draft_2/nested_map/description.json
  services/src/test/resources/describe/wdl_draft_2/objects/description.json
  services/src/test/resources/describe/wdl_draft_2/whitespace_workflow/description.json
  services/src/test/scala/cromwell/services/womtool/impl/WomtoolServiceInCromwellActorSpec.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/TaskDefinitionElementToWomTaskDefinition.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/Util.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/WorkflowDefinitionElementToWomWorkflowDefinition.scala
Labels: 🌲Redwood

#4753 Pass womtool endpoint through CromIAM
  CromIAM/src/main/resources/swagger/cromiam.yaml
  CromIAM/src/main/scala/cromiam/webservice/CromIamApiService.scala
  CromIAM/src/main/scala/cromiam/webservice/WomtoolRouteSupport.scala
  CromIAM/src/test/scala/cromiam/webservice/MockClients.scala
  CromIAM/src/test/scala/cromiam/webservice/SwaggerServiceSpec.scala
  CromIAM/src/test/scala/cromiam/webservice/WomtoolRouteSupportSpec.scala
  docs/api/RESTAPI.md
  engine/src/main/resources/swagger/cromwell.yaml
Labels: Back With Originator ♻️, WaaS, ⭐ Two Thumbs-Up ⭐, 🌲Redwood

#4773 PAPIv2 defensive programming
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/api/request/GetRequestHandler.scala
Labels: Red team, 🌲Redwood

#4736 Remove some very large and hopefully not very necessary metadata indexes.
  database/migration/src/main/resources/metadata_changesets/metadata_index_removals.xml
  database/migration/src/main/resources/sql_metadata_changelog.xml
  database/sql/src/main/scala/cromwell/database/slick/tables/MetadataEntryComponent.scala
Labels: Red team
