Repository broadinstitute/cromwell, pull requests merged in 2020-01, with the labels that each got.

#5330 Ensure a metadata ID is at least a tick old before moving the summary pointer to it [BA-6159]
  database/sql/src/main/scala/cromwell/database/slick/MetadataSlickDatabase.scala
  database/sql/src/main/scala/cromwell/database/sql/MetadataSqlDatabase.scala
  services/src/main/scala/cromwell/services/metadata/impl/MetadataDatabaseAccess.scala
  services/src/main/scala/cromwell/services/metadata/impl/MetadataSummaryRefreshActor.scala
  services/src/test/scala/cromwell/services/metadata/impl/MetadataDatabaseAccessSpec.scala
  services/src/test/scala/cromwell/services/metadata/impl/WriteMetadataActorSpec.scala
Labels: 🚧BLOCKS RELEASE🚧

#5321 GCS 503 retry [BA-5881]
  engine/src/main/scala/cromwell/engine/io/IoActor.scala
  engine/src/test/scala/cromwell/engine/io/IoActorSpec.scala
Labels: 🚧BLOCKS RELEASE🚧

#5349 Exclude us-central1-c zone with broken e2-medium [BA-6168]
  centaur/src/main/resources/integrationTestCases/germline/joint-discovery-gatk/generic.google-papi.options.json
Labels: 🚧BLOCKS RELEASE🚧

#5350 bump cloud-sdk to 275.0.0 [BA-6161]
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/GenomicsFactory.scala
Labels: 🚧BLOCKS RELEASE🚧

#5110 Fixed workflow results and logs copying [BA-5997]
  centaur/src/main/resources/reference.conf
  centaur/src/main/resources/resultsCopyingTestCases/awsWdlResultsCopying.test
  centaur/src/main/resources/resultsCopyingTestCases/awsWdlResultsCopyingRelative.test
  centaur/src/main/resources/resultsCopyingTestCases/gcpWdlResultsCopying.test
  centaur/src/main/resources/resultsCopyingTestCases/gcpWdlResultsCopyingRelative.test
  centaur/src/main/resources/resultsCopyingTestCases/localWdlResultsCopying.test
  centaur/src/main/resources/resultsCopyingTestCases/localWdlResultsCopyingRelative.test
  centaur/src/main/resources/resultsCopyingTestCases/wdlResultsCopying/aws/options.json
  centaur/src/main/resources/resultsCopyingTestCases/wdlResultsCopying/aws/optionsRelative.json
  centaur/src/main/resources/resultsCopyingTestCases/wdlResultsCopying/gcp/options.json
  centaur/src/main/resources/resultsCopyingTestCases/wdlResultsCopying/gcp/optionsRelative.json
  centaur/src/main/resources/resultsCopyingTestCases/wdlResultsCopying/local/options.json
  centaur/src/main/resources/resultsCopyingTestCases/wdlResultsCopying/local/optionsRelative.json
  centaur/src/main/resources/resultsCopyingTestCases/wdlResultsCopying/simpleWorkflow.wdl
  centaur/src/main/scala/centaur/test/CheckFiles.scala
  centaur/src/main/scala/centaur/test/FilesChecker.scala
  centaur/src/main/scala/centaur/test/ObjectCounter.scala
  centaur/src/main/scala/centaur/test/Test.scala
  centaur/src/main/scala/centaur/test/workflow/DirectoryContentCountCheck.scala
  centaur/src/test/scala/centaur/testfilecheck/FileCheckerSpec.scala
  core/src/main/scala/cromwell/core/path/PathCopier.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/finalization/CopyWorkflowLogsActor.scala
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/finalization/CopyWorkflowOutputsActor.scala
  filesystems/s3/src/main/java/org/lerch/s3fs/S3FileSystemProvider.java
  filesystems/s3/src/main/java/org/lerch/s3fs/util/AmazonS3ClientProvider.java
  filesystems/s3/src/main/scala/cromwell/filesystems/s3/S3PathBuilder.scala
  project/Dependencies.scala
Labels: Affects Core Features, Back With Originator ♻️, Community Contribution, On Deck for Review

#5312 Update better-files to 3.8.0 to fix a bug when using zipped-import files.
  CHANGELOG.md
  centaurCwlRunner/src/main/scala/centaur/cwl/CentaurCwlRunner.scala
  core/src/main/scala/cromwell/core/path/BetterFileMethods.scala
  core/src/test/scala/cromwell/core/SimpleIoActor.scala
  engine/src/main/scala/cromwell/engine/io/nio/NioFlow.scala
  languageFactories/language-factory-core/src/test/resources/QC.zip
  languageFactories/language-factory-core/src/test/scala/cromwell/languages/util/ImportResolverSpec.scala
  project/Dependencies.scala
Labels: Community Contribution, On Deck for Review

#5273 Allow GCP global pipeline timeout to be configurable
  cromwell.example.backends/PAPIv2.conf
  docs/backends/Google.md
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/PipelinesApiAsyncBackendJobExecutionActor.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/PipelinesApiConfiguration.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/PipelinesApiConfigurationAttributes.scala
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/api/PipelinesApiRequestFactory.scala
  supportedBackends/google/pipelines/common/src/test/scala/cromwell/backend/google/pipelines/common/PipelinesApiConfigurationAttributesSpec.scala
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/GenomicsFactory.scala
Labels: Community Contribution, On Deck for Review

#5216 Implement recoverAsync for AWS backend [BA-4857]
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchAsyncBackendJobExecutionActor.scala
  supportedBackends/aws/src/test/scala/cromwell/backend/impl/aws/AwsBatchAsyncBackendJobExecutionActorSpec.scala
Labels: Community Contribution, On Deck for Review, ⭐ Two Thumbs-Up ⭐
