Repository broadinstitute/cromwell, pull requests merged in 2020-02, with the labels that each got.

#5259 Fix issue with running cwl files
  centaur/src/main/resources/standardTestCases/cwl_run/1st-tool.cwl
  centaur/src/main/resources/standardTestCases/cwl_run/echo-job.yml
  languageFactories/cwl-v1-0/src/main/scala/languages/cwl/CwlV1_0LanguageFactory.scala
  server/src/main/scala/cromwell/CromwellEntryPoint.scala
  src/ci/bin/testSingleWorkflowRunner.sh
Labels: Community Contribution, On Deck for Review

#5338 WDL 2.0: min and max functions [BA-6158]
  centaur/src/main/resources/standardTestCases/biscayne_as_map_et_al.test
  centaur/src/main/resources/standardTestCases/biscayne_new_engine_functions.test
  centaur/src/main/resources/standardTestCases/wdl_biscayne/biscayne_new_engine_functions/biscayne_new_engine_functions.wdl
  centaur/src/main/scala/centaur/test/Test.scala
  wdl/model/draft3/src/main/scala/wdl/model/draft3/elements/ExpressionElement.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/ast2wdlom/AstToNewExpressionElements.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/consumed/BiscayneExpressionValueConsumers.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/consumed/consumed.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/files/BiscayneFileEvaluators.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/files/files.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/types/BiscayneTypeEvaluators.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/types/types.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/values/BiscayneValueEvaluators.scala
  wdl/transforms/biscayne/src/main/scala/wdl/transforms/biscayne/linking/expression/values/values.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/ast2wdlom/AstNodeToExpressionElement.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/linking/expression/files/EngineFunctionEvaluators.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wdl/WdlWriterImpl.scala
Labels: low priority

#5353 Add workflow option that allows SSH into Google Genomics workers [BA-4966]
  docs/wf_options/Google.md
  supportedBackends/google/pipelines/common/src/main/scala/cromwell/backend/google/pipelines/common/WorkflowOptionKeys.scala
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/GenomicsFactory.scala
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/api/SSHAccessAction.scala
  supportedBackends/google/pipelines/v2beta/src/main/scala/cromwell/backend/google/pipelines/v2beta/LifeSciencesFactory.scala
  supportedBackends/google/pipelines/v2beta/src/main/scala/cromwell/backend/google/pipelines/v2beta/api/SSHAccessAction.scala
Labels: Back With Originator ♻️, Community Contribution, On Deck for Review, ⭐ Two Thumbs-Up ⭐

#5270 Fix TES backend to load preemptible setting from configuration [BA-6004]
  cromwell.example.backends/TES.conf
  docs/backends/TES.md
  supportedBackends/tes/src/main/scala/cromwell/backend/impl/tes/TesRuntimeAttributes.scala
  supportedBackends/tes/src/main/scala/cromwell/backend/impl/tes/TesTask.scala
  supportedBackends/tes/src/test/scala/cromwell/backend/impl/tes/TesInitializationActorSpec.scala
  supportedBackends/tes/src/test/scala/cromwell/backend/impl/tes/TesRuntimeAttributesSpec.scala
  supportedBackends/tes/src/test/scala/cromwell/backend/impl/tes/TesTestConfig.scala
Labels: Community Contribution

#5427 docs: add Ecosystem page
  README.md
  docs/Ecosystem.md
  mkdocs.yml
Labels: Community Contribution

#5426 Allow non-call-cached tasks [BA-6282]
  CHANGELOG.md
  centaur/src/main/resources/standardTestCases/volatile_disables_cache.test
  centaur/src/main/resources/standardTestCases/volatile_disables_cache/volatile_disables_cache.options
  centaur/src/main/resources/standardTestCases/volatile_disables_cache/volatile_disables_cache.wdl
  docs/optimizations/VolatileTasks.md
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/execution/job/EngineJobExecutionActor.scala
  mkdocs.yml
Labels: Community Contribution, low priority

#5423 Reference conda and docker as installation methods.
  CHANGELOG.md
  docs/Getting.md
Labels: Community Contribution, Documentation
