Repository broadinstitute/cromwell, pull requests merged in 2020-07, with the labels that each got.

#5554 Enable call caching of large s3 files
  filesystems/s3/src/main/java/org/lerch/s3fs/S3FileSystemProvider.java
  filesystems/s3/src/test/scala/org/lerch/s3fs/S3FileSystemProviderTest.java
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchJob.scala
Labels: Community Contribution, On Deck for Review

#5562 Allow nested inputs when corresponding meta setting is set to true
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/WorkflowDefinitionElementToWomWorkflowDefinition.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/graph/CallElementToGraphNode.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/graph/IfElementToGraphNode.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/graph/ScatterElementToGraphNode.scala
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/wdlom2wom/graph/WorkflowGraphElementToGraphNode.scala
  womtool/src/test/resources/validate/wdl_draft3/valid/supplied_optional_subwf_sub_inputs_meta_enabled/import_me.wdl
  womtool/src/test/resources/validate/wdl_draft3/valid/supplied_optional_subwf_sub_inputs_meta_enabled/supplied_optional_subwf_sub_inputs_meta_enabled.inputs.json
  womtool/src/test/resources/validate/wdl_draft3/valid/supplied_optional_subwf_sub_inputs_meta_enabled/supplied_optional_subwf_sub_inputs_meta_enabled.wdl
Labels: Community Contribution, Comply with language spec, On Deck for Review, WDL

#5583 Optional string concatenation
  centaur/src/main/resources/standardTestCases/string_interpolation_optional.test
  centaur/src/main/resources/standardTestCases/string_interpolation_optional/string_interpolation_optional.wdl
  wdl/transforms/new-base/src/main/scala/wdl/transforms/base/linking/expression/values/BinaryOperatorEvaluators.scala
Labels: Affects Core Features, Community Contribution, On Deck for Review
