Repository broadinstitute/cromwell, pull requests merged in 2020-04, with the labels that each got.

#5413 optional output handling fix - #5412
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchAsyncBackendJobExecutionActor.scala
Labels: Community Contribution, On Deck for Review

#5469 Stop setting Centaur PostgreSQL schema BA-6351
  centaur/src/it/scala/centaur/AbstractCromwellEngineOrBackendUpgradeTestCaseSpec.scala
  centaur/src/main/resources/reference.conf
Labels: ⭐ Two Thumbs-Up ⭐

#5456 Update relative outputs regex with shard. [BA-6334]
  CHANGELOG.md
  engine/src/main/scala/cromwell/engine/workflow/lifecycle/finalization/CopyWorkflowOutputsActor.scala
Labels: Community Contribution, On Deck for Review, 🐛Bug

#5450 Add xxh64 and fingerprint call-caching strategies to address shortcomings of current strategies. [BA-6335]
  CHANGELOG.md
  build.sbt
  core/src/main/resources/reference_local_provider_config.inc.conf
  cromwell.example.backends/LocalExample.conf
  docs/Configuring.md
  project/Dependencies.scala
  supportedBackends/sfs/src/main/scala/cromwell/backend/impl/sfs/config/ConfigHashingStrategy.scala
  supportedBackends/sfs/src/test/scala/cromwell/backend/impl/sfs/config/ConfigHashingStrategySpec.scala
Labels: Community Contribution, On Deck for Review, Performance, User Requested Improvement, 📞💵Call Caching
