Repository broadinstitute/cromwell, pull requests merged in 2020-06, with the labels that each got.

#5529 Update Google.md
  docs/backends/Google.md
Labels: Community Contribution, On Deck for Review

#5542 Add localization doc for Configuring#local-filesystem-options
  docs/Configuring.md
Labels: Community Contribution

#5468 Issue/5004
  .idea/inspectionProfiles/Project_Default.xml
  filesystems/s3/src/main/java/org/lerch/s3fs/AmazonS3Factory.java
  filesystems/s3/src/main/java/org/lerch/s3fs/S3FileChannel.java
  filesystems/s3/src/main/java/org/lerch/s3fs/S3FileSystemProvider.java
  filesystems/s3/src/main/java/org/lerch/s3fs/S3SeekableByteChannel.java
  filesystems/s3/src/main/java/org/lerch/s3fs/util/AmazonS3ClientProvider.java
  filesystems/s3/src/main/scala/cromwell/filesystems/s3/S3PathBuilder.scala
  filesystems/s3/src/main/scala/cromwell/filesystems/s3/batch/S3BatchCommandBuilder.scala
  filesystems/s3/src/main/scala/cromwell/filesystems/s3/batch/S3BatchIoCommand.scala
  project/Dependencies.scala
  src/ci/bin/testCentaurAws.sh
  src/ci/resources/aws_application.conf
  supportedBackends/aws/src/main/resources/ecs-proxy/Dockerfile
  supportedBackends/aws/src/main/resources/ecs-proxy/build-proxy
  supportedBackends/aws/src/main/resources/ecs-proxy/proxy
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchAsyncBackendJobExecutionActor.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchBackendLifecycleActorFactory.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchJob.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchJobCachingActorHelper.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchJobDefinition.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchJobPaths.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchParameters.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchRuntimeAttributes.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchSingletonActor.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/AwsBatchWorkflowPaths.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/IntervalLimitedAwsJobSubmitActor.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/OccasionalStatusPollingActor.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/README.md
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/RunStatus.scala
  supportedBackends/aws/src/main/scala/cromwell/backend/impl/aws/package.scala
  supportedBackends/aws/src/test/scala/cromwell/backend/impl/aws/AwsBatchRuntimeAttributesSpec.scala
  supportedBackends/aws/src/test/scala/cromwell/backend/impl/aws/AwsBatchTestConfig.scala
Labels: Community Contribution, ⭐ Two Thumbs-Up ⭐
