Repository broadinstitute/cromwell, pull requests merged in 2020-08, with the labels that each got.

#5586 Configurable Google Cloud SDK location [BA-6330]
  docs/backends/Google.md
  supportedBackends/google/pipelines/v2alpha1/src/main/scala/cromwell/backend/google/pipelines/v2alpha1/GenomicsFactory.scala
  supportedBackends/google/pipelines/v2beta/src/main/scala/cromwell/backend/google/pipelines/v2beta/LifeSciencesFactory.scala
Labels: On Deck for Review

#5780 Add womtool outputs command (with tests) [BA-6570]
  womtool/src/main/scala/womtool/WomtoolMain.scala
  womtool/src/main/scala/womtool/cmdline/PartialWomtoolCommandLineArguments.scala
  womtool/src/main/scala/womtool/cmdline/WomtoolCommandLineParser.scala
  womtool/src/main/scala/womtool/outputs/Outputs.scala
  womtool/src/test/resources/outputs/wdl_draft2/scatter/outputs.json
  womtool/src/test/resources/outputs/wdl_draft2/three_step/outputs.json
  womtool/src/test/resources/outputs/wdl_draft3/HaplotypeCallerWF/outputs.json
  womtool/src/test/resources/outputs/wdl_draft3/arrays_v1/outputs.json
  womtool/src/test/resources/outputs/wdl_draft3/callable_imports/outputs.json
  womtool/src/test/resources/outputs/wdl_draft3/cnv_somatic_pair_workflow/outputs.json
  womtool/src/test/resources/outputs/wdl_draft3/joint-discovery-gatk/outputs.json
  womtool/src/test/resources/outputs/wdl_draft3/singlesample_v1/outputs.json
  womtool/src/test/resources/outputs/wdl_draft3/smartseq2_single_sample/outputs.json
  womtool/src/test/resources/outputs/wdl_draft3/three_step/outputs.json
  womtool/src/test/scala/womtool/WomtoolInputsSpec.scala
  womtool/src/test/scala/womtool/WomtoolJsonCommandSpec.scala
  womtool/src/test/scala/womtool/WomtoolMainSpec.scala
  womtool/src/test/scala/womtool/WomtoolOutputsSpec.scala
Labels: Community Contribution, On Deck for Review

#5784 Update containers tutorial to use ${docker_script}
  docs/tutorials/Containers.md
Labels: Community Contribution
